AI Automation for Real State
Posted 1 hour ago
Worldwide
Specialized profiles can help you better highlight your expertise when submitting proposals to jobs like these. Create a specialized profile.

Summary
Summary
We are currently seeking a talented freelancer to join our team and assist us in AI Automation

This role requires someone who is skilled in AI Data Analysis - AI Chatbot - AI Automated Social Media

The ideal candidate will be able to [TASKS/RESPONSIBILITIES).

Responsibilities:

Collaborate with our team to develop and execute effective strategies for AI Automation.

Utilize your expertise in AI Automation to deliver high-quality results.

Communicate regularly with the team to provide updates and discuss project progress.

Meet deadlines and ensure all tasks are completed accurately and efficiently.
Requirements:

Proven experience in  with a strong portfolio of past work.

Proficiency in AI Data Analysis - AI Chatbot - AI Automated Social Media

Excellent communication and collaboration skills.

Ability to work independently and as part of a team.

Attention to detail and a commitment to delivering exceptional results.

In [ ]:
!pip install requests beautifulsoup4 pandas matplotlib seaborn scikit-learn

In [ ]:
!pip install selenium webdriver-manager

In [11]:
import requests
import pandas as pd

# URL of the Divar API for rent apartments in Tehran
url = "https://api.divar.ir/v8/web-search/tehran/rent-apartment "

# Send a GET request to the API
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    data = response.json()  # Convert response to JSON

    # Extracting the list of ads
    posts = data.get('widget_list', [])

    titles = []
    areas = []
    rooms = []
    prices_deposit = []
    prices_rent = []

    # Loop through each post and extract info
    for post in posts:
        data_layer = post.get('data', {})
        
        title = data_layer.get('title')
        metas = data_layer.get('metas', {})

        area = metas.get('area')
        room = metas.get('room_count')
        deposit = metas.get('deposit')
        rent = metas.get('rent')

        titles.append(title)
        areas.append(area)
        rooms.append(room)
        prices_deposit.append(deposit)
        prices_rent.append(rent)

    # Create DataFrame
    df_api = pd.DataFrame({
        'عنوان': titles,
        'مساحت': areas,
        'اتاق': rooms,
        'ودیعه': prices_deposit,
        'اجاره': prices_rent
    })

    print("✅ تعداد آگهی‌های استخراج شده:", len(df_api))
    display(df_api.head())

else:
    print("❌ درخواست ناموفق. کد وضعیت:", response.status_code)

❌ درخواست ناموفق. کد وضعیت: 404

In [12]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # مرورگر بدون نمایش
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# چند ثانیه صبر کن تا صفحه لود شود
time.sleep(5)

# پیدا کردن آگهی‌ها
listings = driver.find_elements(By.CSS_SELECTOR, 'div.post-card-item-af972')

titles = []
areas = []
prices = []

for listing in listings:
    try:
        title = listing.find_element(By.CSS_SELECTOR, 'h2.kt-post-card__title').text
    except:
        title = None

    try:
        area = listing.find_element(By.CSS_SELECTOR, 'div.kt-post-card__bottom-description:nth-child(1)').text.replace('متر', '').strip()
    except:
        area = None

    try:
        price = listing.find_element(By.CSS_SELECTOR, 'div.kt-post-card__description').text.strip()
    except:
        price = None

    titles.append(title)
    areas.append(area)
    prices.append(price)

# ساخت DataFrame
df_selenium = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_selenium))
display(df_selenium.head())

# بستن مرورگر
driver.quit()

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, قیمت]
Index: []

In [13]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # مرورگر بدون نمایش
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# چند ثانیه صبر کن تا صفحه لود شود
time.sleep(5)

# پیدا کردن تمام div ها (یا یک کلاس مشترک)
elements = driver.find_elements(By.TAG_NAME, 'div')

# فقط 10 تا از div ها رو چاپ کنیم که بتونیم ساختار HTML رو بفهمیم
print("🔍 چند نمونه از div های موجود در صفحه:")
for i, el in enumerate(elements[:10]):
    print(f"{i+1}. {el.get_attribute('class')} | {el.text[:100]}...")

# بستن مرورگر
driver.quit()

🔍 چند نمونه از div های موجود در صفحه:
1.  | تهران
دسته‌ها
دستیار خرید
آزمایشی
دستیار خرید (آزمایشی)
دیوار من
چت
پشتیبانی
ثبت آگهی
۷۵,۱۶۸ آگهی در...
2.  | ...
3. a11y-menu__container-eac90 | ...
4. kt-rich-tooltip__trigger | تهران...
5. nav-bar__category-mega-box | دسته‌ها
دستیار خرید
آزمایشی
دستیار خرید (آزمایشی)
دیوار من
چت
پشتیبانی
ثبت آگهی...
6. kt-dropdown-menu category-mega-dropdown-f35f1 | دسته‌ها...
7. nav-bar__search-container | ...
8.  | ...
9. full-width kt-nav-text-field | ...
10. kt-nav-text-field__field | ...

In [14]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # مرورگر بدون نمایش
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# چند ثانیه صبر کن تا صفحه لود شود
time.sleep(5)

# پیدا کردن تمام div ها
elements = driver.find_elements(By.TAG_NAME, 'div')

# فیلتر کردن div هایی که محتوایشون شامل "اجاره آپارتمان" است
print("🔍 div هایی که شامل عبارت 'اجاره آپارتمان' هستند:")
found = False
for el in elements:
    text = el.text.strip()
    if 'اجاره آپارتمان' in text:
        print(f"- {text[:100]}...")
        found = True

if not found:
    print("❌ هیچ آگهی اجاره آپارتمانی پیدا نشد.")

# بستن مرورگر
driver.quit()

🔍 div هایی که شامل عبارت 'اجاره آپارتمان' هستند:
❌ هیچ آگهی اجاره آپارتمانی پیدا نشد.

In [15]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.XPATH, '//div[contains(@class, "kt-post-card__title")]'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند. صفحه شاید تغییر کرده.")

# پیدا کردن تمام آگهی‌ها با XPath دینامیک
listings = driver.find_elements(By.XPATH, '//div[contains(@class, "post-card-item")]')

titles = []
areas = []
prices = []

print(f"✅ {len(listings)} آگهی پیدا شد. در حال استخراج...")

for listing in listings:
    try:
        title = listing.find_element(By.XPATH, './/h2[contains(@class, "kt-post-card__title")]').text
    except:
        title = None

    try:
        area = listing.find_element(By.XPATH,
                                     './/div[contains(@class, "kt-post-card__bottom-description") and contains(text(), "متر")]').text.replace(
            'متر', '').strip()
    except:
        area = None

    try:
        price = listing.find_element(By.XPATH,
                                      './/div[contains(@class, "kt-post-card__description")]').text.strip()
    except:
        price = None

    titles.append(title)
    areas.append(area)
    prices.append(price)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head())

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
❌ المان‌های آگهی پیدا نشدند. صفحه شاید تغییر کرده.
✅ 0 آگهی پیدا شد. در حال استخراج...

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, قیمت]
Index: []

In [17]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند. صفحه شاید تغییر کرده.")

# پیدا کردن تمام آگهی‌ها با CSS Selector
listings = driver.find_elements(By.CSS_SELECTOR, 'div.unsafe-kt-post-card')

titles = []
areas = []
prices = []

print(f"✅ {len(listings)} آگهی پیدا شد. در حال استخراج...")

for listing in listings:
    try:
        title = listing.find_element(By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title').text
    except:
        title = None

    try:
        # پیدا کردن مساحت (مثال: "205 متر")
        area_text = listing.find_element(By.CSS_SELECTOR, 'div.unsafe-kt-post-card__description').text
        if 'متر' in area_text:
            area = area_text.split('متر')[0].strip()
        else:
            area = None
    except:
        area = None

    try:
        # پیدا کردن قیمت (مثال: "و دیعه: ۲,۲۰۰,۰۰۰,۰۰۰ تومان")
        price_text = listing.find_element(By.CSS_SELECTOR, 'div.unsafe-kt-post-card__description').text
        if 'و دیعه:' in price_text:
            price = price_text.split('و دیعه: ')[1].split(' تومان')[0].replace(',', '').strip()
        elif 'اجاره:' in price_text:
            price = price_text.split('اجاره: ')[1].split(' تومان')[0].replace(',', '').strip()
        else:
            price = None
    except:
        price = None

    titles.append(title)
    areas.append(area)
    prices.append(price)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head())

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
✅ المان‌های آگهی پیدا شدند.
✅ 0 آگهی پیدا شد. در حال استخراج...

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, قیمت]
Index: []

In [18]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند.")

# ⬇️ اسکرول کردن به پایین برای لود تمام آگهی‌ها
print("⬇️ در حال اسکرول کردن به پایین...")
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(3)  # صبر کن تا محتوا لود بشه

# پیدا کردن تمام آگهی‌ها با CSS Selector (فقط h2 ها رو تست می‌کنیم)
all_titles = driver.find_elements(By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title')

titles = []
areas = []
prices = []

print(f"✅ {len(all_titles)} آگهی پیدا شد. در حال استخراج...")

for title in all_titles:
    titles.append(title.text)

# چون فقط عنوان رو می‌تونیم بگیریم، دیگه متغیرهای دیگه None می‌شن
areas = [None] * len(titles)
prices = [None] * len(titles)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head())

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
✅ المان‌های آگهی پیدا شدند.
⬇️ در حال اسکرول کردن به پایین...
✅ 6 آگهی پیدا شد. در حال استخراج...

✅ تعداد آگهی‌های استخراج شده: 6

                                              عنوان مساحت  قیمت
0  اجاره آپارتمان ۶۰ متری ۲ خوابه طبقه ۴ در باغ فیض  None  None
1  ۲۷۰متر نوساز / برند /فول مشاعات /لوکیشن تاپ دروس  None  None
2               ۵۵ کارون طوس طبقه1نزدیک مترو شادمان  None  None
3                                   ۱۶۰متر رهن کامل  None  None
4                     پاسداران ۱۵۵متر/نوساز/تکواحدی  None  None

In [19]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd
import re

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند.")

# ⬇️ اسکرول چندباره به پایین
for i in range(3):  # 3 بار اسکرول کن
    print(f"⬇️ اسکرول #{i+1}")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # صبر کن تا محتوا لود بشه

# پیدا کردن تمام آگهی‌ها
all_titles = driver.find_elements(By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title')

titles = [title.text for title in all_titles]

# استخراج مساحت از عنوان
def extract_area(title):
    match = re.search(r'(\d+)[\s\/]*متر', title)
    return int(match.group(1)) if match else None

areas = [extract_area(title) for title in titles]

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
✅ المان‌های آگهی پیدا شدند.
⬇️ اسکرول #1
⬇️ اسکرول #2
⬇️ اسکرول #3

✅ تعداد آگهی‌های استخراج شده: 6

                                            عنوان  مساحت
0  اپارتمان ۵۵متر یکخوابه طبقه اول جنت اباد مرکزی     55
1       فرمانیه غربی 110 متر ۳ خواب ۸۵ متر ۲ خواب    110
2            ۷۵متر/سعادت آباد/صراف شمالی/خوش نقشه     75
3         میرداماد150متر/3خواب/تکواحدی/قابل تبدیل    150
4               خواجه عبدالله ۱۶۰ متر ۳خواب نوساز    160
5                        75 متری کوچه اشرفی زاده.     75

In [20]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd
import re

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک جدید
url = "https://divar.ir/s/tehran/rent-apartment/jeyhoon?districts=1001%2C1002%2C1006%2C654%2C195%2C197%2C196%2C1029%2C284%2C1005%2C312&map_bbox=51.354522705078125%2C35.66758728027344%2C51.37498474121094%2C35.700321197509766&map_interaction=list_only_used&map_place_hash=1%7C1001%2C1002%2C1006%2C657%7Capartment-rent "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند.")

# ⬇️ اسکرول چندباره به پایین
for i in range(5):  # 5 بار اسکرول کن
    print(f"⬇️ اسکرول #{i+1}")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # صبر کن تا محتوا لود بشه

# پیدا کردن تمام آگهی‌ها
all_titles = driver.find_elements(By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title')

titles = [title.text for title in all_titles]

# استخراج مساحت از عنوان
def extract_area(title):
    match = re.search(r'(\d+)[\s\/]*متر', title)
    return int(match.group(1)) if match else None

areas = [extract_area(title) for title in titles]

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
✅ المان‌های آگهی پیدا شدند.
⬇️ اسکرول #1
⬇️ اسکرول #2
⬇️ اسکرول #3
⬇️ اسکرول #4
⬇️ اسکرول #5

✅ تعداد آگهی‌های استخراج شده: 6

                                               عنوان  مساحت
0                     اجاره آپارتمان نقلی و خوش نقشه    NaN
1      ۸۸متر فول امکانات/ کلیدنخورده/ تک واحدی/تخلیه   88.0
2              50متر/فول/پارکینگ موتور/جیحون، مرتضوی   50.0
3  اجاره هوم آفیس،۴۰ متر، ثبت وامکان گرفتن وام اجاره   40.0
4  ۵۳ متر تکواحدی با پارکینگ غیر مزاحم. سالن پرده...   53.0
5                 اپارتمان۶۴متر/ارومیه/تکخواب/دسترسی   64.0

In [22]:
import requests
from bs4 import BeautifulSoup
import json
import re
import pandas as pd

# URL صفحه
url = "https://divar.ir/s/tehran/rent-apartment "

# درخواست به سرور
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# پیدا کردن بلاک JSON
script_tag = soup.find('script', {'id': '__NEXT_DATA__'})
data = json.loads(script_tag.string)

# مسیر داده‌های آگهی
posts = data['props']['pageProps']['webAdList']['listData']

titles = []
areas = []
prices = []

for post in posts:
    title = post.get("title")
    description = post.get("description")
    
    titles.append(title)
    
    # استخراج مساحت
    area_match = re.search(r'(\d+)[\s\/]*متر', description) if description else None
    areas.append(int(area_match.group(1)) if area_match else None)
    
    # استخراج قیمت (مثال: "ودیعه: ۲,۵۰۰,۰۰۰,۰۰۰ تومان")
    price_match = re.search(r'ودیعه:\s*([\d\,]+)\s*تومان', description) if description else None
    prices.append(price_match.group(1).replace(',', '') if price_match else None)

# ساخت DataFrame
df_json = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_json))
display(df_json.head(10))

AttributeError: 'NoneType' object has no attribute 'string'

In [24]:
import re
import json
import pandas as pd

# خواندن فایل یا متن HTML
with open('Pasted_Text_1747572450500.txt', 'r', encoding='utf-8') as f:
    html_content = f.read()

# پیدا کردن تمام بلاک‌های JSON با regex
pattern = r'"token":"([^"]+)","title":"([^"]*)","description":"([^"]*)"'
matches = re.findall(pattern, html_content)

titles = []
descriptions = []
areas = []
prices = []

for match in matches:
    token, title, description = match
    
    titles.append(title)
    descriptions.append(description)
    
    # استخراج مساحت
    area_match = re.search(r'(\d+)[\s\/]*متر', title + " " + description)
    areas.append(int(area_match.group(1)) if area_match else None)
    
    # استخراج قیمت (ودیعه)
    price_match = re.search(r'ودیعه:\s*([\d\,]+)\s*تومان', description)
    prices.append(price_match.group(1).replace(',', '') if price_match else None)

# ساخت DataFrame
df_regex = pd.DataFrame({
    'عنوان': titles,
    'توضیحات': descriptions,
    'مساحت': areas,
    'قیمت': prices
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_regex))
display(df_regex[['عنوان', 'مساحت', 'قیمت']])

FileNotFoundError: [Errno 2] No such file or directory: 'Pasted_Text_1747572450500.txt'

In [25]:
import re
import pandas as pd

# ⬇️ اینجا متن HTML رو مستقیم درون کد گذاشتیم
html_content = """
<script>window.__PRELOADED_STATE__ = {"nb":{"listTopWidgets":[{"widgetType":"POST_LIST_HEADLINE","text":"اجاره و رهن آپارتمان، خانه و سوییت در زنجان و ۱۱ محلهٔ دیگر تهران","KEY_PROP_NAME":"efdf926f-cf77-4f3a-aff2-5b397a66d8e8","visibilityConditions":[]}],"listWidgets":[{"type":"WIDGET","data":{"widgetType":"POST_ROW","token":"Aao4yg-A","title":"همخونه همخانه نیازمندم","topDescription":"ودیعه: ۵۰,۰۰۰,۰۰۰ تومان","middleDescription":"اجاره: ۶,۰۰۰,۰۰۰ تومان","bottomDescription":"در دکتر هوشیار","redText":"پله شده","action":{"as":"link"

...

متر، ثبت وامکان گرفتن وام اجاره"},{"name":"۵۳ متر تکواحدی با پارکینگ غیر مزاحم. سالن پرده خور","url":"https://divar.ir/v/ ۵۳-متر-تکواحدی-با-پارکینگ-غیر-مزاحم-سالن-پرده-خور/AapUthb7","accommodationCategory":"آپارتمان","@context":"https://schema.org ","numberOfRooms":"یک","floorSize":{"@type":"QuantitativeValue","value":"53","unitCode":"MTK"},"geo":{"address":"تهران, جیحون","latitude":"35.691192501346","longitude":"51.366855079884","@type":"GeoCoordinates"},"web_info":{"title":"۵۳ متر تکواحدی با پارکینگ غیر مزاحم. سالن پرده خور","city_persian":"تهران"
...
"""

# الگو برای استخراج JSON‌های مهم شامل title و قیمت و مساحت
pattern = r'"token":"([^"]+)","title":"([^"]*)","description":"([^"]*)"'
matches = re.findall(pattern, html_content)

titles = []
areas = []
prices_deposit = []
prices_rent = []

for match in matches:
    token, title, description = match

    titles.append(title)

    # 🔍 استخراج مساحت
    area = None
    area_match = re.search(r'"floorSize":\{"@type":"QuantitativeValue","value":"(\d+)"', description + title + html_content)
    if area_match:
        area = int(area_match.group(1))
    areas.append(area)

    # 🔍 استخراج قیمت (ودیعه)
    deposit_price = None
    deposit_match = re.search(r'ودیعه:\s*([\d\,]+)\s*تومان', description)
    if deposit_match:
        deposit_price = deposit_match.group(1).replace(',', '')
    prices_deposit.append(deposit_price)

    # 🔍 استخراج قیمت (اجاره)
    rent_price = None
    rent_match = re.search(r'اجاره:\s*([\d\,]+)\s*تومان', description)
    if rent_match:
        rent_price = rent_match.group(1).replace(',', '')
    prices_rent.append(rent_price)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'ودیعه': prices_deposit,
    'اجاره': prices_rent
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, ودیعه, اجاره]
Index: []

In [26]:
import re
import pandas as pd

# خواندن فایل txt با رمزگذاری درست
file_path = 'Pasted_Text_1747572949033.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# پیدا کردن تمام آگهی‌ها با regex
pattern = r'"token":"([^"]+)","title":"([^"]*)","topDescription":"([^"]*)","middleDescription":"([^"]*)","bottomDescription":"([^"]*)"'
matches = re.findall(pattern, content)

titles = []
areas = []
deposits = []
rents = []
locations = []

for match in matches:
    token, title, top_desc, middle_desc, bottom_desc = match

    titles.append(title)
    locations.append(bottom_desc)

    # 🔍 استخراج مساحت از عنوان یا توضیحات
    area_match = re.search(r'(\d+)\s*متر', title + " " + top_desc + " " + middle_desc)
    areas.append(int(area_match.group(1)) if area_match else None)

    # 🔍 استخراج ودیعه
    deposit_match = re.search(r'ودیعه:\s*([\d\,]+)\s*تومان', top_desc)
    deposits.append(deposit_match.group(1).replace(',', '') if deposit_match else None)

    # 🔍 استخراج اجاره
    rent_match = re.search(r'اجاره:\s*([\d\,]+)\s*تومان', middle_desc)
    rents.append(rent_match.group(1).replace(',', '') if rent_match else None)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'ودیعه': deposits,
    'اجاره': rents,
    'موقعیت': locations
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 26

,عنوان,مساحت,ودیعه,اجاره,موقعیت
0,همخونه همخانه نیازمندم,NaN,۵۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,در دکتر هوشیار
1,۸۸متر فول امکانات\u002F کلیدنخورده\u002F تک وا...,88.0,۱۱۷۰۰۰۰۰۰۰,None,مشاورین املاک گل محمدی شعبه ۲ در جیحون
2,50متر\u002Fفول\u002Fپارکینگ موتور\u002Fجیحون، ...,50.0,۱۵۰۰۰۰۰۰۰,۱۳۰۰۰۰۰۰,آژانس املاک همپا در جیحون
3,اجاره هوم آفیس،۴۰ متر، ثبت وامکان گرفتن وام اجاره,40.0,۱۳۰۰۰۰۰۰۰,۱۰۵۰۰۰۰۰,دقایقی پیش در هفت چنار
4,۵۳ متر تکواحدی با پارکینگ غیر مزاحم. سالن پرده...,53.0,۲۵۰۰۰۰۰۰۰,۱۱۵۰۰۰۰۰,آژانس مشاورین املاک طهرانی در جیحون
5,اپارتمان۶۴متر\u002Fارومیه\u002Fتکخواب\u002Fدسترسی,64.0,۸۰۰۰۰۰۰۰۰,۱۰۰۰۰۰,املاک حافظ در آذربایجان
6,۵۰ متر\u002Fفول امکانات\u002Fغرق نور,50.0,۳۵۰۰۰۰۰۰۰,۸۵۰۰۰۰۰,مشاور اسدی در استاد معین
7,۴۲ متر‌\u002Fپارکینگ غیر مزاحم\u002Fکردکاظمی ب...,42.0,۳۰۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,آژانس املاک خانه برتر در بریانک
8,۶۵متر\u002Fبازسازی\u002Fتکواحدی\u002Fآذربایجان,65.0,۳۵۰۰۰۰۰۰۰,۱۶۰۰۰۰۰۰,گروه مشاورین املاک آفرند در آذربایجان
9,۵۵ کارون طوس طبقه1نزدیک مترو شادمان,NaN,۲۰۰۰۰۰۰۰۰,۱۲۰۰۰۰۰۰,آژانس املاک طلوع در جیحون

In [30]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'pasted_divar_data.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# الگوهای regex برای استخراج اطلاعات
title_matches = re.findall(r'"name":"([^"]+)"', content)
area_matches = re.findall(r'"value":"(\d+)\s*متر"', content)
deposit_matches = re.findall(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', content)
rent_matches = re.findall(r'اجاره:\s*(\d[\d\,]*)\s*تومان', content)

# استخراج تمام داده‌ها با regex عمومی‌تر (در صورت نیاز)
general_title_matches = re.findall(r'alt="([^"]+)"', content)

# ترکیب همه عنوان‌ها
all_titles = title_matches + general_title_matches

# تنظیم طول لیست‌ها به یک اندازه
min_len = min(len(all_titles), len(area_matches), len(deposit_matches), len(rent_matches))

titles = all_titles[:min_len]
areas = area_matches[:min_len]
deposits = deposit_matches[:min_len]
rents = rent_matches[:min_len]

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'ودیعه': deposits,
    'اجاره': rents
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, ودیعه, اجاره]
Index: []

In [31]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'pasted_divar_data.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# الگوهای Regex برای استخراج
title_matches = re.findall(r'"title":"(.*?)"', content)
top_descs = re.findall(r'"topDescription":"(.*?)"', content)
mid_descs = re.findall(r'"middleDescription":"(.*?)"', content)
bot_descs = re.findall(r'"bottomDescription":"(.*?)"', content)

# استخراج مساحت، ودیعه و اجاره
areas = []
deposits = []
rents = []
locations = []

for i in range(len(title_matches)):
    title = title_matches[i] if i < len(title_matches) else None
    top_desc = top_descs[i] if i < len(top_descs) else None
    mid_desc = mid_descs[i] if i < len(mid_descs) else None
    bot_desc = bot_descs[i] if i < len(bot_descs) else None

    # استخراج مساحت
    area_match = re.search(r'(\d+)\s*متر', title + " " + (top_desc or "") + " " + (mid_desc or ""))
    areas.append(int(area_match.group(1)) if area_match else None)

    # استخراج ودیعه
    deposit_match = re.search(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', top_desc or "")
    deposits.append(deposit_match.group(1).replace(',', '') if deposit_match else None)

    # استخراج اجاره
    rent_match = re.search(r'اجاره:\s*(\d[\d\,]*)\s*تومان', mid_desc or "")
    rents.append(rent_match.group(1).replace(',', '') if rent_match else None)

    # ذخیره موقعیت
    locations.append(bot_desc or None)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': title_matches,
    'مساحت': areas,
    'ودیعه': deposits,
    'اجاره': rents,
    'موقعیت': locations
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 118

,عنوان,مساحت,ودیعه,اجاره,موقعیت
0,همخونه همخانه نیازمندم,NaN,۵۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,در دکتر هوشیار
1,اجاره مشترک (همخونه),NaN,۱۰۰۰۰۰۰,۱۰۰۰۰۰,در استاد معین
2,اجاره آپارتمان ۴۴ متری ۱ خوابه طبقه ۲ در جیحون,44.0,۱۰۰۰۰۰۰۰۰,۱۴۰۰۰۰۰۰,دقایقی پیش در جیحون
3,۵۵ متر فول امکانات گذر ۱۰ متری بر اصلی,55.0,۶۰۰۰۰۰۰۰۰,None,دپارتمان کاوه در جی
4,اجاره آپارتمان ۵۸ متری ۱ خوابه در طوس,58.0,۷۰۰۰۰۰۰۰۰,۱۴۰۰۰۰۰۰,دقایقی پیش در دکتر هوشیار
5,60متر\u002F تک واحدی با پارکینگ\u002F۱۳ متری,60.0,۵۰۰۰۰۰۰۰۰,۳۰۰۰۰۰۰,دقایقی پیش در جی
6,بهنود یادگارطوس(نوساز)۱۰۶متر,106.0,۵۰۰۰۰۰۰۰۰,۲۵۰۰۰۰۰۰,در جیحون
7,۶۶متر\u002Fدوخواب\u002Fتکواحدی\u002Fآسانسور\u0...,66.0,۳۵۰۰۰۰۰۰۰,۱۵۰۰۰۰۰۰,دقایقی پیش در آذربایجان
8,۴۳متر \u002Fهمکف \u002Fفول بازسازی \u002F غرق نور,43.0,۲۵۰۰۰۰۰۰۰,۴۰۰۰۰۰۰,آژانس امید در سلیمانی
9,۷۰ متر ۲ خواب \u002F تک واحدی,70.0,۴۰۰۰۰۰۰۰۰,۵۰۰۰۰۰۰,مشاورین املاک احمدزاده در هفت چنار

In [32]:
# ذخیره در فایل CSV
df_final.to_csv('divar_rent_data.csv', index=False, encoding='utf-8-sig')
print("✅ فایل CSV با موفقیت ذخیره شد!")

✅ فایل CSV با موفقیت ذخیره شد!

In [33]:
import pandas as pd

# خواندن فایل CSV
df = pd.read_csv('divar_rent_data.csv')

# نمایش داده‌ها با شماره‌گذاری ردیف
df.index = df.index + 1  # شماره‌گذاری از ۱ شروع بشه
print("✅ داده‌های ذخیره شده در فایل CSV:")
display(df)

✅ داده‌های ذخیره شده در فایل CSV:

,عنوان,مساحت,ودیعه,اجاره,موقعیت
1,همخونه همخانه نیازمندم,NaN,۵۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,در دکتر هوشیار
2,اجاره مشترک (همخونه),NaN,۱۰۰۰۰۰۰,۱۰۰۰۰۰,در استاد معین
3,اجاره آپارتمان ۴۴ متری ۱ خوابه طبقه ۲ در جیحون,44.0,۱۰۰۰۰۰۰۰۰,۱۴۰۰۰۰۰۰,دقایقی پیش در جیحون
4,۵۵ متر فول امکانات گذر ۱۰ متری بر اصلی,55.0,۶۰۰۰۰۰۰۰۰,NaN,دپارتمان کاوه در جی
5,اجاره آپارتمان ۵۸ متری ۱ خوابه در طوس,58.0,۷۰۰۰۰۰۰۰۰,۱۴۰۰۰۰۰۰,دقایقی پیش در دکتر هوشیار
...,...,...,...,...,...
114,رهن ۴۷ متر - ۱خوابه - مرتضوی,47.0,NaN,NaN,NaN
115,آپارتمان ۴۰ متری,40.0,NaN,NaN,NaN
116,۱۰۸متر ۲خواب(پارکینگ،انباری)همکف/استادمعین پازوکی,108.0,NaN,NaN,NaN
117,65متر 1خواب فول بازسازی شده رهن کامل,65.0,NaN,NaN,NaN
118,رهن اجاره ۵۰ متر آپارتمان پارکینگدار سی متری جی,50.0,NaN,NaN,NaN

In [ ]:
# تنظیم pandas برای نمایش تمام ردیف‌ها
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# نمایش DataFrame
display(df_final)

In [35]:
import re
import json
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# الگو برای پیدا کردن بلاک JSON
json_match = re.search(r'window.__PRELOADED_STATE__\s*=\s*({.*?});', content, re.DOTALL)

if json_match:
    # تبدیل رشته JSON به دیکشنری
    try:
        json_str = json_match.group(1)
        data = json.loads(json_str)
        
        # استخراج لیست آگهی‌ها
        posts = data.get('props', {}).get('pageProps', {}).get('webAdList', {}).get('listData', [])
        
        titles = []
        areas = []
        deposits = []
        rents = []
        locations = []

        for post in posts:
            data_layer = post.get('data', {})
            
            title = data_layer.get('title')
            description = data_layer.get('description', '')
            bottom_desc = data_layer.get('bottom_description', '')

            titles.append(title)
            locations.append(bottom_desc)

            # استخراج مساحت
            area_match = re.search(r'(\d+)\s*متر', title + " " + description)
            areas.append(int(area_match.group(1)) if area_match else None)

            # استخراج ودیعه
            deposit_match = re.search(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', description)
            deposits.append(deposit_match.group(1).replace(',', '') if deposit_match else None)

            # استخراج اجاره
            rent_match = re.search(r'اجاره:\s*(\d[\d\,]*)\s*تومان', description)
            rents.append(rent_match.group(1).replace(',', '') if rent_match else None)

        # ساخت DataFrame
        df_house_rent = pd.DataFrame({
            'عنوان': titles,
            'مساحت': areas,
            'ودیعه': deposits,
            'اجاره': rents,
            'موقعیت': locations
        })

        print("✅ تعداد آگهی‌های استخراج شده:", len(df_house_rent))
        display(df_house_rent.head(10))

    except json.JSONDecodeError as e:
        print("❌ خطا در دکد کردن JSON:", e)
else:
    print("❌ داده JSON پیدا نشد")

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, ودیعه, اجاره, موقعیت]
Index: []

In [41]:
import json
import pandas as pd
import os

# Check current working directory
print("Current Working Directory:", os.getcwd())

# Define the correct file path
file_path = 'divar_fullrent.txt'  # Make sure this file exists in your folder

posts = []

# Open and read the file line by line
with open(file_path, 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        try:
            data = json.loads(line.strip())

            # Only process WIDGET type with POST_ROW widgetType
            if isinstance(data, dict) and data.get('type') == 'WIDGET':
                widget_data = data.get('data', {})
                if widget_data.get('widgetType') == 'POST_ROW':
                    post_info = {
                        'token': widget_data.get('token'),
                        'title': widget_data.get('title'),
                        'topDescription': widget_data.get('topDescription'),
                        'middleDescription': widget_data.get('middleDescription'),
                        'bottomDescription': widget_data.get('bottomDescription'),
                        'url_suffix': widget_data.get('action', {}).get('props', {}).get('to')
                    }
                    posts.append(post_info)

        except json.JSONDecodeError:
            continue  # Skip lines that can't be parsed

# Create DataFrame
df_posts = pd.DataFrame(posts)

# Show result
if not df_posts.empty:
    print("\n✅ Successfully loaded data:")
    display(df_posts.head())
else:
    print("\n❌ No valid data found. Please check the file content or structure.")

Current Working Directory: /Users/macbookpro/AMIR_DATA/00_Project/VSCode__project/1_Machine_learning/with_AI/ML_Models/simulation_upwork/real_estate_ml_analysis

❌ No valid data found. Please check the file content or structure.

In [42]:
import re
import json
import pandas as pd

# File path
file_path = 'divar_fullrent.txt'

# Read the full HTML content
with open(file_path, 'r', encoding='utf-8') as f:
    html_content = f.read()

# Find all JSON objects inside "window.__PRELOADED_STATE__" (where Divar stores its data)
match = re.search(r'window\.__PRELOADED_STATE__\s*=\s*({.*?});\s*\(function', html_content, re.DOTALL)

if match:
    try:
        # Load the main JSON data
        raw_json = match.group(1)
        data = json.loads(raw_json)

        # Navigate to the posts list
        posts_data = data.get('widgets', {}).get('list', [])

        posts = []
        for post in posts_data:
            if isinstance(post, dict) and post.get('widgetType') == 'POST_ROW':
                post_info = {
                    'token': post.get('token'),
                    'title': post.get('title'),
                    'topDescription': post.get('topDescription'),
                    'middleDescription': post.get('middleDescription'),
                    'bottomDescription': post.get('bottomDescription'),
                    'url_suffix': post.get('action', {}).get('props', {}).get('to')
                }
                posts.append(post_info)

        # Create DataFrame
        df_posts = pd.DataFrame(posts)
        
        if not df_posts.empty:
            print("✅ Successfully loaded data:")
            display(df_posts.head())
        else:
            print("❌ No POST_ROW widgets found in the JSON.")
    
    except json.JSONDecodeError as e:
        print("❌ Failed to parse JSON:", e)
else:
    print("❌ Could not find JSON data in HTML file.")

❌ Could not find JSON data in HTML file.

In [45]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# الگوهای Regex برای استخراج
title_matches = re.findall(r'"title":"(.*?)"', content)
top_descs = re.findall(r'"topDescription":"(.*?)"', content)
mid_descs = re.findall(r'"middleDescription":"(.*?)"', content)
bot_descs = re.findall(r'"bottomDescription":"(.*?)"', content)

# استخراج مساحت، ودیعه و اجاره
areas = []
deposits = []
rents = []
locations = []

for i in range(len(title_matches)):
    title = title_matches[i] if i < len(title_matches) else None
    top_desc = top_descs[i] if i < len(top_descs) else None
    mid_desc = mid_descs[i] if i < len(mid_descs) else None
    bot_desc = bot_descs[i] if i < len(bot_descs) else None

    # استخراج مساحت
    area_match = re.search(r'(\d+)\s*متر', title + " " + (top_desc or "") + " " + (mid_desc or ""))
    areas.append(int(area_match.group(1)) if area_match else None)

    # استخراج ودیعه
    deposit_match = re.search(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', top_desc or "")
    deposits.append(deposit_match.group(1).replace(',', '') if deposit_match else None)

    # استخراج اجاره
    rent_match = re.search(r'اجاره:\s*(\d[\d\,]*)\s*تومان', mid_desc or "")
    rents.append(rent_match.group(1).replace(',', '') if rent_match else None)

    # ذخیره موقعیت
    locations.append(bot_desc or None)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': title_matches,
    'مساحت': areas,
    'ودیعه': deposits,
    'اجاره': rents,
    'موقعیت': locations
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 107

,عنوان,مساحت,ودیعه,اجاره,موقعیت
0,خانه دربستی چهار خوابه,NaN,۷۰۰۰۰۰۰۰۰,۵۲۰۰۰۰۰,در نواب
1,۱۰۰ متر ۳ طبقه \u002Fخ آزادی جنب مترو توحید \u...,100.0,۵۰۰۰۰۰۰۰۰,۶۵۰۰۰۰۰۰,آژانس املاک بزرگ سناتور با ۲شعبه فعال در جیحون
2,خانه ویلایی ۲۵۰ متر,250.0,۴۰۰۰۰۰۰۰۰,۵۰۰۰۰۰۰۰,دقایقی پیش در استاد معین
3,100 متری \u002Fدر بستی\u002F,100.0,۷۵۰۰۰۰۰۰۰,۱۰۰۰۰۰,آژانس امید در هفت چنار
4,واحد دربست خانه 100متری دو طبقه جیحون سپه,100.0,۳۵۰۰۰۰۰۰۰,۲۸۰۰۰۰۰۰,املاک بزرگ نهال در جیحون
5,اجاره خانه ویلایی ۷۰ متری ۳ خوابه در جیحون,70.0,۴۵۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,آژانس املاک دریا در جیحون
6,خانه نقلی۲۵ متری ۲طبقه دربست خانواده مجرد,25.0,۳۹۰۰۰۰۰۰۰,۱۰۰۰۰۰,۲ ساعت پیش در هاشمی
7,اجاره خانه ویلایی ۱۲۰ متری ۵ خوابه در جی,120.0,۴۰۰۰۰۰۰۰۰,۱۸۰۰۰۰۰۰,۲ ساعت پیش در جی
8,اجاره خانه ویلایی ۴۰ متری ۲ خوابه در استاد معین,40.0,۲۱۰۰۰۰۰۰۰,۱۰۰۰۰۰۰۰,۳ ساعت پیش در استاد معین
9,اجاره خانه ویلایی ۱۲ متری ۱ خوابه در سلسبیل,12.0,۲۰۰۰۰۰۰,۷۵۰۰۰۰۰,۴ ساعت پیش در سلسبیل

In [46]:
# ذخیره به صورت CSV
df_final.to_csv('real_estate_data.csv', index=False, encoding='utf-8-sig')
print("✅ دیتا با موفقیت در فایل 'real_estate_data.csv' ذخیره شد.")

✅ دیتا با موفقیت در فایل 'real_estate_data.csv' ذخیره شد.

In [47]:
# ذخیره به صورت pickle
df_final.to_pickle('real_estate_data.pkl')
print("✅ دیتا با موفقیت در فایل 'real_estate_data.pkl' ذخیره شد.")

✅ دیتا با موفقیت در فایل 'real_estate_data.pkl' ذخیره شد.

In [ ]:
# نمایش تمام ردیف‌ها در Jupyter
pd.set_option('display.max_rows', None)
display(df_final)

In [51]:
import re
import json
import pandas as pd

# ۱. خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as f:
    html_content = f.read()

# ۲. الگوی دقیق‌تر برای پیدا کردن JSON دیوار
match = re.search(r'window\.__PRELOADED_STATE__\s*=\s*(\{.*?\});', html_content, re.DOTALL)

if match:
    try:
        # ۳. استخراج JSON و لود کردن
        raw_json = match.group(1)
        
        # ۴. تبدیل به دیکشنری پایتون
        data = json.loads(raw_json)

        # ۵. دسترسی به لیست آگهی‌ها
        posts_data = data.get('widgets', {}).get('list', [])

        # ۶. استخراج فیلدهای مهم
        posts = []
        for post in posts_data:
            if isinstance(post, dict) and post.get('widgetType') == 'POST_ROW':
                token = post.get('token')
                title = post.get('title')
                top_desc = post.get('topDescription')
                mid_desc = post.get('middleDescription')
                bot_desc = post.get('bottomDescription')

                # استخراج مساحت، ودیعه، اجاره
                area_match = re.search(r'(\d+)\s*(?:متر|متري)', title + " " + (top_desc or "") + " " + (mid_desc or ""))
                area = int(area_match.group(1)) if area_match else None

                deposit_match = re.search(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', top_desc or "")
                deposit = deposit_match.group(1).replace(',', '') if deposit_match else None

                rent_match = re.search(r'اجاره:\s*(\d[\d\,]*)\s*تومان', mid_desc or "")
                rent = rent_match.group(1).replace(',', '') if rent_match else None

                # ذخیره موقعیت
                location = bot_desc

                posts.append({
                    'token': token,
                    'عنوان': title,
                    'مساحت': area,
                    'ودیعه': deposit,
                    'اجاره': rent,
                    'موقعیت': location
                })

        # ۷. ساخت DataFrame
        df_final = pd.DataFrame(posts)

        # ۸. تبدیل اعداد فارسی به انگلیسی
        def fa_to_en_numbers(text):
            if not isinstance(text, str):
                return text
            fa_digits = '۰۱۲۳۴۵۶۷۸۹'
            en_digits = '0123456789'
            translation_table = str.maketrans(fa_digits, en_digits)
            return text.translate(translation_table)

        df_final['ودیعه'] = df_final['ودیعه'].apply(fa_to_en_numbers)
        df_final['اجاره'] = df_final['اجاره'].apply(fa_to_en_numbers)

        # ۹. ذخیره به CSV
        df_final.to_csv('real_estate_data_clean.csv', index=False, encoding='utf-8-sig')
        print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
        print(df_final.head(10))

    except json.JSONDecodeError as e:
        print("❌ خطا در خواندن JSON:", e)
else:
    print("❌ JSON دیوار در فایل پیدا نشد.")

KeyError: 'ودیعه'

In [52]:
print("✅ ستون‌های DataFrame:")
print(df_final.columns.tolist())

✅ ستون‌های DataFrame:
[]

In [54]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    html_content = file.read()

# الگوهای Regex برای استخراج
title_matches = re.findall(r'alt="([^"]+)"', html_content)
price_deposit = re.findall(r'ودیعه:\s*([\d۰-۹,]+)\s*تومان', html_content)
price_rent = re.findall(r'اجاره:\s*([\d۰-۹,]+)\s*تومان', html_content)
area_matches = re.findall(r'(\d+)\s*متر', ' '.join(title_matches))

# تابع تبدیل عدد فارسی به انگلیسی
def fa_to_en_numbers(text):
    if not isinstance(text, str):
        return text
    fa_digits = '۰۱۲۳۴۵۶۷۸۹'
    en_digits = '0123456789'
    translation_table = str.maketrans(fa_digits, en_digits)
    return text.translate(translation_table)

# استخراج موقعیت از عنوان (مثلاً "املاک کاندید در آذربایجان")
location_matches = []
for title in title_matches:
    loc_match = re.search(r'(?:در|در منطقه|در محله|،|\.|در)\s*([آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]{2,})', title)
    location_matches.append(loc_match.group(1).strip() if loc_match else None)

# تنظیم اعداد فارسی به انگلیسی
cleaned_areas = [int(fa_to_en_numbers(area)) if area else None for area in area_matches]
cleaned_deposits = [int(fa_to_en_numbers(dep).replace(',', '')) if dep else None for dep in price_deposit]
cleaned_rents = [int(fa_to_en_numbers(rent).replace(',', '')) if rent else None for rent in price_rent]

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': title_matches,
    'مساحت': cleaned_areas,
    'ودیعه': cleaned_deposits,
    'اجاره': cleaned_rents,
    'موقعیت': location_matches
})

# ذخیره به CSV
df_final.to_csv('real_estate_data_final.csv', index=False, encoding='utf-8-sig')

# نمایش خروجی
print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
print(df_final.head(10))

ValueError: All arrays must be of the same length

In [55]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    html_content = file.read()

# الگو برای پیدا کردن هر آگهی
post_pattern = re.compile(
    r'<.*?alt="(.*?)".*?(?:ودیعه:\s*([\d۰-۹,]+)\s*تومان)?.*?(?:اجاره:\s*([\d۰-۹,]+)\s*تومان)?.*?(?:(\d+)\s*متر).*?(?:در|در منطقه|در محله|،|\.|در)\s*([آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]{2,})', 
    re.DOTALL
)

# استخراج اطلاعات همزمان
posts = []
for match in post_pattern.finditer(html_content):
    title = match.group(1)
    deposit = match.group(2)
    rent = match.group(3)
    area = match.group(4)
    location = match.group(5)

    posts.append({
        'عنوان': title.strip() if title else None,
        'مساحت': int(area) if area else None,
        'ودیعه': deposit.strip() if deposit else None,
        'اجاره': rent.strip() if rent else None,
        'موقعیت': location.strip() if location else None
    })

# ساخت DataFrame
df_final = pd.DataFrame(posts)

# تبدیل عدد فارسی به انگلیسی
def fa_to_en_numbers(text):
    if not isinstance(text, str):
        return text
    fa_digits = '۰۱۲۳۴۵۶۷۸۹'
    en_digits = '0123456789'
    translation_table = str.maketrans(fa_digits, en_digits)
    return text.translate(translation_table)

df_final['ودیعه'] = df_final['ودیعه'].apply(lambda x: fa_to_en_numbers(x).replace(',', '') if isinstance(x, str) else x)
df_final['اجاره'] = df_final['اجاره'].apply(lambda x: fa_to_en_numbers(x).replace(',', '') if isinstance(x, str) else x)

# ذخیره به CSV
df_final.to_csv('real_estate_data_final.csv', index=False, encoding='utf-8-sig')

# نمایش خروجی
print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
print(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 14
                                             عنوان  مساحت ودیعه اجاره  \
0                                       نشان دیوار    100  None  None
1  ۱۰۰ متر ۳ طبقه /خ آزادی جنب مترو توحید /پارکینگ    250  None  None
2                              خانه ویلایی ۲۵۰ متر    100  None  None
3                               100 متری /در بستی/    100  None  None
4       واحد دربست خانه 100متری دو طبقه  جیحون سپه     70  None  None
5  اجاره خانه ویلایی ۴۰ متری ۲ خوابه در استاد معین     12  None  None
6      اجاره خانه ویلایی ۱۲ متری ۱ خوابه در سلسبیل    120  None  None
7               ۱۲۰متر چهار خواب خوش نرسیده به طوس    100  None  None
8               ۱۰۰ متر/کلنگی/سینا غربی/مترو کمیل/    150  None  None
9                  150 متر فول بازسازی کمیل شیرازی    150  None  None

       موقعیت
0       جیحون
1  استاد معین
2        بستی
3    بست خانه
4       جیحون
5      سلسبیل
6   آذربایجان
7        نواب
8    هفت چنار
9     بستی در

In [64]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    html_content = file.read()

# الگو برای پیدا کردن هر آگهی با regex هوشمندانه
post_pattern = re.compile(
    r'alt="(.*?)".*?(?:ودیعه:\s*([\d۰-۹,]+)\s*تومان)?.*?(?:اجاره:\s*([\d۰-۹,]+)\s*تومان)?.*?(\d+)\s*متر.*?(?:در|،|\.|در منطقه|در محله)\s*([آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]{2,})',
    re.DOTALL
)

posts = []

for match in post_pattern.finditer(html_content):
    title = match.group(1)
    deposit = match.group(2)
    rent = match.group(3)
    area = match.group(4)
    location = match.group(5)

    posts.append({
        'عنوان': title.strip() if title else None,
        'مساحت': int(area) if area else None,
        'ودیعه': deposit.strip() if deposit else None,
        'اجاره': rent.strip() if rent else None,
        'موقعیت': location.strip() if location else None
    })

# تبدیل عدد فارسی به انگلیسی
def fa_to_en_numbers(text):
    if not isinstance(text, str):
        return text
    fa_digits = '۰۱۲۳۴۵۶۷۸۹'
    en_digits = '0123456789'
    translation_table = str.maketrans(fa_digits, en_digits)
    return text.translate(translation_table)

df_final = pd.DataFrame(posts)
df_final['ودیعه'] = df_final['ودیعه'].apply(lambda x: fa_to_en_numbers(x).replace(',', '') if isinstance(x, str) and x else x)
df_final['اجاره'] = df_final['اجاره'].apply(lambda x: fa_to_en_numbers(x).replace(',', '') if isinstance(x, str) and x else x)

# ذخیره دیتا
df_final.to_csv('real_estate_data_final.csv', index=False, encoding='utf-8-sig')

# نمایش خروجی
print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
print(df_final)

✅ تعداد آگهی‌های استخراج شده: 14
                                                عنوان  مساحت ودیعه اجاره  \
0                                          نشان دیوار    100  None  None
1     ۱۰۰ متر ۳ طبقه /خ آزادی جنب مترو توحید /پارکینگ    250  None  None
2                                 خانه ویلایی ۲۵۰ متر    100  None  None
3                                  100 متری /در بستی/    100  None  None
4          واحد دربست خانه 100متری دو طبقه  جیحون سپه     70  None  None
5     اجاره خانه ویلایی ۴۰ متری ۲ خوابه در استاد معین     12  None  None
6         اجاره خانه ویلایی ۱۲ متری ۱ خوابه در سلسبیل    120  None  None
7                  ۱۲۰متر چهار خواب خوش نرسیده به طوس    100  None  None
8                  ۱۰۰ متر/کلنگی/سینا غربی/مترو کمیل/    150  None  None
9                     150 متر فول بازسازی کمیل شیرازی    150  None  None
10  ۱۵۰ متر واحد دربستی در ۲ طبقه کاملا مجزا . با ...    300  None  None
11       ویلایی ۳۰۰ متری ۵ خوابه در نزدیک مترو شادمان     50  None  None
12        ۲طبقه دربست ۵۰ متری سرویس کامل مرتضوی جیحون    120  None  None
13                       ۱۲۰ متر دربستی دوطبقه بریانک    100  None  None

                موقعیت
0                جیحون
1           استاد معین
2                 بستی
3             بست خانه
4                جیحون
5               سلسبیل
6            آذربایجان
7                 نواب
8             هفت چنار
9              بستی در
10   نزدیک مترو شادمان
11               جیحون
12  بستی دوطبقه بریانک
13                باره

In [7]:
import requests
import json

url = "https://api.divar.ir/v8/web-search/tehran/rent-villa"

payload = {
    "json_schema": {
        "districts": {
            "value": [
                1002, 1005, 1006, 1029, 195, 196, 197, 284, 312, 654, 657
            ]
        }
    },
    "last-post-date": None
}

headers = {
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0"
}

response = requests.post(url, headers=headers, json=payload)
data = response.json()

# بررسی داده‌های موجود در کلید sections
sections = data.get("sections", [])
for section in sections:
    widgets = section.get("widgets", [])
    for widget in widgets:
        if widget.get("widget_type") == "POST_ROW":
            post_data = widget.get("data", {})
            title = post_data.get("title", "")
            district = post_data.get("district", "")
            price = post_data.get("price", "")
            token = post_data.get("token", "")
            post_url = f"https://divar.ir/v/{token}"
            print(f"{title} | {district} | {price} | {post_url}")

In [9]:
import requests
import json

url = "https://api.divar.ir/v8/web-search/tehran/rent-villa"

payload = {
    "json_schema": {
        "districts": {
            "value": [
                1002, 1005, 1006, 1029, 195, 196, 197, 284, 312, 654, 657
            ]
        }
    },
    "last-post-date": None
}

headers = {
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0"
}

response = requests.post(url, headers=headers, json=payload)
data = response.json()

# برای بررسی دقیق ساختار پاسخ
print(json.dumps(data, indent=2, ensure_ascii=False))

{
  "description": "Method Not Allowed",
  "status": 405,
  "message": "Method POST not allowed for URL /web_search/tehran/rent-villa"
}

In [10]:
import requests
import json

url = "https://api.divar.ir/v8/web-search/tehran"

payload = {
    "json_schema": {
        "category": {
            "value": "rent_villa"
        },
        "districts": {
            "value": [
                1002, 1005, 1006, 1029, 195, 196, 197, 284, 312, 654, 657
            ]
        }
    },
    "last-post-date": None
}

headers = {
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0"
}

response = requests.post(url, headers=headers, json=payload)
data = response.json()

ads_found = False
for section in data.get("sections", []):
    for widget in section.get("widgets", []):
        if widget.get("widget_type") == "POST_ROW":
            post = widget.get("data", {})
            title = post.get("title", "")
            district = post.get("district", "")
            price = post.get("price", "")
            token = post.get("token", "")
            post_url = f"https://divar.ir/v/{token}"
            print(f"{title} | {district} | {price} | {post_url}")
            ads_found = True

if not ads_found:
    print("⚠️ هیچ آگهی‌ای پیدا نشد.")

⚠️ هیچ آگهی‌ای پیدا نشد.

In [11]:
payload = {
    "json_schema": {
        "category": {
            "value": "rent_villa"
        }
    },
    "last-post-date": None
}

In [13]:
import requests
import json

url = "https://api.divar.ir/v8/web-search/tehran"

payload = {
    "json_schema": {
        "category": {
            "value": "rent_villa"
        }
    },
    "last-post-date": None
}

headers = {
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0"
}

response = requests.post(url, headers=headers, json=payload)

try:
    data = response.json()
except Exception as e:
    print("❌ خطا در تبدیل پاسخ به JSON:", e)
    print(response.text)
    exit()

print(json.dumps(data, indent=2, ensure_ascii=False))  # نمایش کامل پاسخ

{
  "description": "Method Not Allowed",
  "status": 405,
  "message": "Method POST not allowed for URL /web_search/tehran"
}

In [14]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

# لینک با فیلترهای دلخواه
url = "https://divar.ir/s/tehran/rent-villa/tehran-zanjan?districts=1002%2C1005%2C1006%2C1029%2C195%2C196%2C197%2C284%2C312%2C654%2C657"

# پیکربندی Selenium
options = Options()
options.add_argument("--headless")  # برای اجرای بدون باز کردن مرورگر
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(options=options)
driver.get(url)

# صبر برای لود شدن آگهی‌ها
time.sleep(5)

# پیدا کردن آگهی‌ها
ads = driver.find_elements(By.CSS_SELECTOR, "div.kt-post-card.kt-post-card--outlined")

if not ads:
    print("⚠️ هیچ آگهی‌ای پیدا نشد.")
else:
    for ad in ads:
        try:
            title = ad.find_element(By.CSS_SELECTOR, "h2.kt-post-card__title").text
            price = ad.find_element(By.CSS_SELECTOR, "div.kt-post-card__description").text
            location = ad.find_element(By.CSS_SELECTOR, "span.kt-post-card__bottom-description").text
            link = ad.find_element(By.TAG_NAME, "a").get_attribute("href")
            print(f"{title} | {location} | {price} | {link}")
        except Exception as e:
            print("خطا در خواندن یک آگهی:", e)

driver.quit()

⚠️ هیچ آگهی‌ای پیدا نشد.

In [15]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

# آدرس صفحه دیوار برای ویلا در مناطق خاص تهران
url = "https://divar.ir/s/tehran/rent-villa/tehran-zanjan?districts=1002%2C1005%2C1006%2C1029%2C195%2C196%2C197%2C284%2C312%2C654%2C657"

# تنظیمات Chrome
options = Options()
options.add_argument("--headless")  # اگر می‌خوای مرورگر باز نشه
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(options=options)
driver.get(url)

try:
    # صبر کن تا کارت‌های آگهی لود بشن
    wait = WebDriverWait(driver, 15)
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "div.kt-post-card")))
    
    ads = driver.find_elements(By.CSS_SELECTOR, "div.kt-post-card")
    
    if not ads:
        print("⚠️ هنوز هیچ آگهی‌ای پیدا نشد.")
        print("🪵 HTML صفحه:")
        print(driver.page_source[:3000])  # فقط ۳۰۰۰ کاراکتر اول سورس HTML برای بررسی
    else:
        for ad in ads:
            try:
                title = ad.find_element(By.CSS_SELECTOR, "h2.kt-post-card__title").text
                price = ad.find_element(By.CSS_SELECTOR, "div.kt-post-card__description").text
                location = ad.find_element(By.CSS_SELECTOR, "span.kt-post-card__bottom-description").text
                link = ad.find_element(By.TAG_NAME, "a").get_attribute("href")
                print(f"{title} | {location} | {price} | {link}")
            except Exception as e:
                print("خطا در خواندن یک آگهی:", e)

except Exception as e:
    print("❌ خطا در انتظار بارگذاری آگهی‌ها:", e)

finally:
    driver.quit()

❌ خطا در انتظار بارگذاری آگهی‌ها: Message:
Stacktrace:
0   chromedriver                        0x000000010cf038a8 chromedriver + 5986472
1   chromedriver                        0x000000010cefa9da chromedriver + 5949914
2   chromedriver                        0x000000010c9b3600 chromedriver + 415232
3   chromedriver                        0x000000010ca05304 chromedriver + 750340
4   chromedriver                        0x000000010ca05521 chromedriver + 750881
5   chromedriver                        0x000000010ca55204 chromedriver + 1077764
6   chromedriver                        0x000000010ca2b33d chromedriver + 906045
7   chromedriver                        0x000000010ca52566 chromedriver + 1066342
8   chromedriver                        0x000000010ca2b0e3 chromedriver + 905443
9   chromedriver                        0x000000010c9f761d chromedriver + 693789
10  chromedriver                        0x000000010c9f8281 chromedriver + 696961
11  chromedriver                        0x000000010cec1570 chromedriver + 5715312
12  chromedriver                        0x000000010cec5435 chromedriver + 5731381
13  chromedriver                        0x000000010ce9bec0 chromedriver + 5562048
14  chromedriver                        0x000000010cec5e6b chromedriver + 5733995
15  chromedriver                        0x000000010ce8add4 chromedriver + 5492180
16  chromedriver                        0x000000010cee8a88 chromedriver + 5876360
17  chromedriver                        0x000000010cee8c50 chromedriver + 5876816
18  chromedriver                        0x000000010cefa5a1 chromedriver + 5948833
19  libsystem_pthread.dylib             0x00007ff818e084e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff818e03f6b thread_start + 15

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time

options = Options()
# options.add_argument("--headless")  # فعلاً غیرفعال باشه

driver = webdriver.Chrome(options=options)
driver.get("https://divar.ir/s/tehran/rent-villa")

time.sleep(10)  # صبر کنیم کل آگهی‌ها لود بشه

print("✅ صفحه باز شد. لطفاً چک کن آیا آگهی می‌بینی؟")

input("⬅️ بعد از بررسی در مرورگر، Enter رو بزن برای ادامه...")

html = driver.page_source
print(html[:3000])  # فقط بخشی از سورس برای بررسی

driver.quit()

✅ صفحه باز شد. لطفاً چک کن آیا آگهی می‌بینی؟

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time

options = Options()
# options.add_argument("--headless")  # غیرفعال باشه برای دیدن صفحه

user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
options.add_argument(f"user-agent={user_agent}")

driver = webdriver.Chrome(options=options)
driver.get("https://divar.ir/s/tehran/rent-villa")

time.sleep(10)

print("✅ صفحه باز شد. لطفاً چک کن آیا آگهی می‌بینی؟")

input("⬅️ بعد از بررسی در مرورگر، Enter رو بزن برای ادامه...")

html = driver.page_source
print(html[:3000])
driver.quit()

✅ صفحه باز شد. لطفاً چک کن آیا آگهی می‌بینی؟

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
# options.add_argument("--headless")  # اگر دوست داری مرورگر باز نشه
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
options.add_argument(f"user-agent={user_agent}")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)

driver = webdriver.Chrome(options=options)
driver.get("https://divar.ir/s/tehran/rent-villa")

time.sleep(10)  # صبر برای لود کامل آگهی‌ها

ads = driver.find_elements(By.CSS_SELECTOR, "div.kt-post-card")

if not ads:
    print("⚠️ هیچ آگهی‌ای پیدا نشد.")
else:
    for ad in ads:
        try:
            title = ad.find_element(By.CSS_SELECTOR, "h2.kt-post-card__title").text
            price = ad.find_element(By.CSS_SELECTOR, "div.kt-post-card__description").text
            location = ad.find_element(By.CSS_SELECTOR, "span.kt-post-card__bottom-description").text
            link = ad.find_element(By.TAG_NAME, "a").get_attribute("href")
            print(f"{title} | {location} | {price} | {link}")
        except Exception as e:
            print("خطا در خواندن یک آگهی:", e)

driver.quit()

⚠️ هیچ آگهی‌ای پیدا نشد.

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
# options.add_argument("--headless")  # اگر لازم بود
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
options.add_argument(f"user-agent={user_agent}")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)

driver = webdriver.Chrome(options=options)
driver.get("https://divar.ir/s/tehran/rent-villa")

time.sleep(10)  # صبر برای لود

# پیدا کردن تگ‌هایی که کلاس‌شون شامل 'post' هست
elements = driver.find_elements(By.CSS_SELECTOR, "[class*='post']")

print(f"تعداد المنت‌های شامل 'post' در کلاس: {len(elements)}")
for i, el in enumerate(elements[:10]):
    print(f"\n-- المنت شماره {i+1} --")
    print(el.get_attribute("outerHTML")[:1000])  # 1000 کاراکتر اول تگ

driver.quit()

تعداد المنت‌های شامل 'post' در کلاس: 127

-- المنت شماره 1 --
<div class="post-list-eb562"><div style="width: 100%; height: 4784px; position: relative;"><div style="top: 0px; left: 0px; width: 100%; position: absolute; padding-top: 1472px;"><div data-index="9" class="post-list__items-container-e44b2"><div class="full-width-widget-col-c8bd0"><article data-testid="container" class="unsafe-kt-post-card unsafe-kt-post-card--outlined unsafe-kt-post-card"><a class="unsafe-kt-post-card__action" href="/v/ویلایی-۴۰-متری-دو-طبقه-در-هاشمی-پارکینگ-موتور/AajskhxL"><div class="unsafe-kt-post-card__body"><div class="unsafe-kt-post-card__info"><h2 class="unsafe-kt-post-card__title">ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور</h2><div class="unsafe-kt-post-card__description">ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__description">اجاره: ۶,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__bottom"><span class="unsafe-kt-post-card__red-text">نردبان شده</span><span class="unsafe-kt-post-card__bottom-description kt-text-truncate" title="آژان

-- المنت شماره 2 --
<div data-index="9" class="post-list__items-container-e44b2"><div class="full-width-widget-col-c8bd0"><article data-testid="container" class="unsafe-kt-post-card unsafe-kt-post-card--outlined unsafe-kt-post-card"><a class="unsafe-kt-post-card__action" href="/v/ویلایی-۴۰-متری-دو-طبقه-در-هاشمی-پارکینگ-موتور/AajskhxL"><div class="unsafe-kt-post-card__body"><div class="unsafe-kt-post-card__info"><h2 class="unsafe-kt-post-card__title">ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور</h2><div class="unsafe-kt-post-card__description">ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__description">اجاره: ۶,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__bottom"><span class="unsafe-kt-post-card__red-text">نردبان شده</span><span class="unsafe-kt-post-card__bottom-description kt-text-truncate" title="آژانس سناتور در زنجان">آژانس سناتور در زنجان</span></div></div><div class="unsafe-kt-post-card-thumbnail"><div><div class="kt-image-block kt-image-block--radius-sm" title="ویلایی ۴۰ م

-- المنت شماره 3 --
<article data-testid="container" class="unsafe-kt-post-card unsafe-kt-post-card--outlined unsafe-kt-post-card"><a class="unsafe-kt-post-card__action" href="/v/ویلایی-۴۰-متری-دو-طبقه-در-هاشمی-پارکینگ-موتور/AajskhxL"><div class="unsafe-kt-post-card__body"><div class="unsafe-kt-post-card__info"><h2 class="unsafe-kt-post-card__title">ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور</h2><div class="unsafe-kt-post-card__description">ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__description">اجاره: ۶,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__bottom"><span class="unsafe-kt-post-card__red-text">نردبان شده</span><span class="unsafe-kt-post-card__bottom-description kt-text-truncate" title="آژانس سناتور در زنجان">آژانس سناتور در زنجان</span></div></div><div class="unsafe-kt-post-card-thumbnail"><div><div class="kt-image-block kt-image-block--radius-sm" title="ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور" style="padding-bottom: 100%;"><div class="kt-placeholder kt-ima

-- المنت شماره 4 --
<a class="unsafe-kt-post-card__action" href="/v/ویلایی-۴۰-متری-دو-طبقه-در-هاشمی-پارکینگ-موتور/AajskhxL"><div class="unsafe-kt-post-card__body"><div class="unsafe-kt-post-card__info"><h2 class="unsafe-kt-post-card__title">ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور</h2><div class="unsafe-kt-post-card__description">ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__description">اجاره: ۶,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__bottom"><span class="unsafe-kt-post-card__red-text">نردبان شده</span><span class="unsafe-kt-post-card__bottom-description kt-text-truncate" title="آژانس سناتور در زنجان">آژانس سناتور در زنجان</span></div></div><div class="unsafe-kt-post-card-thumbnail"><div><div class="kt-image-block kt-image-block--radius-sm" title="ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور" style="padding-bottom: 100%;"><div class="kt-placeholder kt-image-block__image"><i class="kt-icon kt-icon-camera-off-o kt-icon--xl kt-placeholder__icon"></i></div></div></div

-- المنت شماره 5 --
<div class="unsafe-kt-post-card__body"><div class="unsafe-kt-post-card__info"><h2 class="unsafe-kt-post-card__title">ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور</h2><div class="unsafe-kt-post-card__description">ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__description">اجاره: ۶,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__bottom"><span class="unsafe-kt-post-card__red-text">نردبان شده</span><span class="unsafe-kt-post-card__bottom-description kt-text-truncate" title="آژانس سناتور در زنجان">آژانس سناتور در زنجان</span></div></div><div class="unsafe-kt-post-card-thumbnail"><div><div class="kt-image-block kt-image-block--radius-sm" title="ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور" style="padding-bottom: 100%;"><div class="kt-placeholder kt-image-block__image"><i class="kt-icon kt-icon-camera-off-o kt-icon--xl kt-placeholder__icon"></i></div></div></div></div></div>

-- المنت شماره 6 --
<div class="unsafe-kt-post-card__info"><h2 class="unsafe-kt-post-card__title">ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور</h2><div class="unsafe-kt-post-card__description">ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__description">اجاره: ۶,۰۰۰,۰۰۰ تومان</div><div class="unsafe-kt-post-card__bottom"><span class="unsafe-kt-post-card__red-text">نردبان شده</span><span class="unsafe-kt-post-card__bottom-description kt-text-truncate" title="آژانس سناتور در زنجان">آژانس سناتور در زنجان</span></div></div>

-- المنت شماره 7 --
<h2 class="unsafe-kt-post-card__title">ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور</h2>

-- المنت شماره 8 --
<div class="unsafe-kt-post-card__description">ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان</div>

-- المنت شماره 9 --
<div class="unsafe-kt-post-card__description">اجاره: ۶,۰۰۰,۰۰۰ تومان</div>

-- المنت شماره 10 --
<div class="unsafe-kt-post-card__bottom"><span class="unsafe-kt-post-card__red-text">نردبان شده</span><span class="unsafe-kt-post-card__bottom-description kt-text-truncate" title="آژانس سناتور در زنجان">آژانس سناتور در زنجان</span></div>

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
# options.add_argument("--headless")  # اگر می‌خوای مرورگر باز نشه
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
options.add_argument(f"user-agent={user_agent}")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)

driver = webdriver.Chrome(options=options)
driver.get("https://divar.ir/s/tehran/rent-villa")

time.sleep(10)  # صبر برای لود کامل

ads = driver.find_elements(By.CSS_SELECTOR, "article.unsafe-kt-post-card")

if not ads:
    print("⚠️ هیچ آگهی‌ای پیدا نشد.")
else:
    for ad in ads:
        try:
            title = ad.find_element(By.CSS_SELECTOR, "h2.unsafe-kt-post-card__title").text
            price_elems = ad.find_elements(By.CSS_SELECTOR, "div.unsafe-kt-post-card__description")
            # معمولا ودیعه و اجاره هستن، اولی ودیعه، دومی اجاره
            deposit = price_elems[0].text if len(price_elems) > 0 else ""
            rent = price_elems[1].text if len(price_elems) > 1 else ""
            location = ad.find_element(By.CSS_SELECTOR, "span.unsafe-kt-post-card__bottom-description").get_attribute("title")
            link = ad.find_element(By.CSS_SELECTOR, "a.unsafe-kt-post-card__action").get_attribute("href")
            print(f"{title} | {location} | {deposit} | {rent} | https://divar.ir{link}")
        except Exception as e:
            print("خطا در خواندن یک آگهی:", e)

driver.quit()

همکف ۱۲۰ متری کارگاه / رضویه | املاک مهماندوست در کاروان | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.irhttps://divar.ir/v/%D9%87%D9%85%DA%A9%D9%81-%DB%B1%DB%B2%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DA%A9%D8%A7%D8%B1%DA%AF%D8%A7%D9%87-%D8%B1%D8%B6%D9%88%DB%8C%D9%87/AaqoQS4Z
رهن خانه ویلایی ۸۰ متری در آذری | ۲۱ ساعت پیش در آذری | ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.irhttps://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B8%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1-%D8%A2%D8%B0%D8%B1%DB%8C/AaqgAkq0
خانه مستعقلاتی منطقه ۱۷ | ۲۱ ساعت پیش در وصفنارد | ودیعه: ۴۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.irhttps://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D9%85%D8%B3%D8%AA%D8%B9%D9%82%D9%84%D8%A7%D8%AA%DB%8C-%D9%85%D9%86%D8%B7%D9%82%D9%87-%DB%B1%DB%B7/AaqgAL5F
اجاره مستغلات امیرآباد بالای جلال ۵۲۰ متر بنا | ۲۱ ساعت پیش در امیرآباد | ودیعه: ۱,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۳۰,۰۰۰,۰۰۰ تومان | https://divar.irhttps://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%D8%A7%D9%85%DB%8C%D8%B1%D8%A2%D8%A8%D8%A7%D8%AF-%D8%A8%D8%A7%D9%84%D8%A7%DB%8C-%D8%AC%D9%84%D8%A7%D9%84-%DB%B5%DB%B2%DB%B0-%D9%85%D8%AA%D8%B1-%D8%A8%D9%86%D8%A7/AapMPZvV
اجاره سوییت ۲۰متری | ۲۱ ساعت پیش در فرحزاد | ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.irhttps://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%B3%D9%88%DB%8C%DB%8C%D8%AA-%DB%B2%DB%B0%D9%85%D8%AA%D8%B1%DB%8C/AapMOJd9

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
options.add_argument(f"user-agent={user_agent}")

driver = webdriver.Chrome(options=options)
driver.get("https://divar.ir/s/tehran/rent-villa")

time.sleep(10)

ads = driver.find_elements(By.CSS_SELECTOR, "article.unsafe-kt-post-card")

if not ads:
    print("⚠️ هیچ آگهی‌ای پیدا نشد.")
else:
    for ad in ads:
        try:
            title = ad.find_element(By.CSS_SELECTOR, "h2.unsafe-kt-post-card__title").text
            price_elems = ad.find_elements(By.CSS_SELECTOR, "div.unsafe-kt-post-card__description")
            deposit = price_elems[0].text if len(price_elems) > 0 else ""
            rent = price_elems[1].text if len(price_elems) > 1 else ""
            location = ad.find_element(By.CSS_SELECTOR, "span.unsafe-kt-post-card__bottom-description").get_attribute("title")
            link = ad.find_element(By.CSS_SELECTOR, "a.unsafe-kt-post-card__action").get_attribute("href")
            if not link.startswith("http"):
                link = "https://divar.ir" + link
            print(f"{title} | {location} | {deposit} | {rent} | {link}")
        except Exception as e:
            print("خطا در خواندن یک آگهی:", e)

driver.quit()

خانه اجاره ای | ۲۰ ساعت پیش در خزانه | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۱,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%A7%DB%8C/AaqgRRI7
رهن خانه ویلایی | ۲۰ ساعت پیش در امین حضور | ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C/AaqgxMqw
ساختمان دربست یک جا سعادت آباد 400 متر | مشاور سعید رضا حاجی وند در آسمان | ودیعه: ۶,۰۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%B3%D8%A7%D8%AE%D8%AA%D9%85%D8%A7%D9%86-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%DB%8C%DA%A9-%D8%AC%D8%A7-%D8%B3%D8%B9%D8%A7%D8%AF%D8%AA-%D8%A2%D8%A8%D8%A7%D8%AF-400-%D9%85%D8%AA%D8%B1/AaX4id_B
67 متری کلنگی دربستی مناسب انبار و تولیدی | مشاورین املاک بزرگ برج در ظهیرآباد | ودیعه: ۳۵۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/67-%D9%85%D8%AA%D8%B1%DB%8C-%DA%A9%D9%84%D9%86%DA%AF%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D8%A7%D9%86%D8%A8%D8%A7%D8%B1-%D9%88-%D8%AA%D9%88%D9%84%DB%8C%D8%AF%DB%8C/Aaa8Y4hW
خانه دربستی ۶۰ متری | ۲۰ ساعت پیش در اتابک | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۳,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%DB%B6%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C/Aaqchqvz
900 متر ویلایی زعفرانیه محمودیه مناسب همه مشاغل | کارشناس امور ملکی منطقه ۱ صادق پور در محمودیه | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۶۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/900-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%B2%D8%B9%D9%81%D8%B1%D8%A7%D9%86%DB%8C%D9%87-%D9%85%D8%AD%D9%85%D9%88%D8%AF%DB%8C%D9%87-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D9%87%D9%85%D9%87-%D9%85%D8%B4%D8%A7%D8%BA%D9%84/AaXsw5SI
اجاره ویلای دو طبقه 60 متری دربسته | ۲۰ ساعت پیش در کوی هفدهم شهریور | ودیعه: ۳۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۹,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C-%D8%AF%D9%88-%D8%B7%D8%A8%D9%82%D9%87-60-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%D9%87/AaqUB-zf
رهن خانه ویلایی ۸۰۰ متری ۴ خوابه در زعفرانیه | املاک آتی زعفرانیه در زعفرانیه | ودیعه: ۳۰,۰۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B8%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B4-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%B2%D8%B9%D9%81%D8%B1%D8%A7%D9%86%DB%8C%D9%87/AaqUhpk9
دیلمان جنوبی اجاره خانه ویلایی ۱۵۰ متری | ۲۰ ساعت پیش در دیلمان | ودیعه: ۲,۵۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%AF%DB%8C%D9%84%D9%85%D8%A7%D9%86-%D8%AC%D9%86%D9%88%D8%A8%DB%8C-%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C/AaqMxoVi
اجاره خانه ویلایی ۷۰ متری ۲ خوابه در گمرک | ۲۱ ساعت پیش در گمرک | ودیعه: ۳۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۳,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B7%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B2-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%DA%AF%D9%85%D8%B1%DA%A9/AaqAxW7F
رهن خانه ویلایی ۱۳۰ متری ۵ خوابه در شوش | در شوش | ودیعه: ۱,۱۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B3%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%B4%D9%88%D8%B4/Aaqcw71y

In [5]:
import requests
from bs4 import BeautifulSoup
import time

base_url = "https://divar.ir/s/tehran/rent-villa/tehran-zanjan"
params = {
    "districts": "1002,1005,1006,1029,195,196,197,284,312,654,657",
    "map_bbox": "51.33375549316406,35.659141540527344,51.38261413574219,35.70193862915039",
    "map_interaction": "list_only_used",
    "map_place_hash": "1|1001,1002,1005,1006,1029,195,196,197,284,312,654,657|apartment-rent",
    "page": 1
}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}

listings = []

while len(listings) < 100:
    print(f"Fetching page {params['page']}...")
    response = requests.get(base_url, params=params, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    ads = soup.find_all("div", {"class": "post-card-item"})
    if not ads:
        print("No more ads found.")
        break

    for ad in ads:
        title = ad.find("div", {"class": "kt-post-card__title"}).text.strip() if ad.find("div", {"class": "kt-post-card__title"}) else "No title"
        price = ad.find("div", {"class": "kt-post-card__description"}).text.strip() if ad.find("div", {"class": "kt-post-card__description"}) else "No price"
        link = "https://divar.ir" + ad.find("a")["href"] if ad.find("a") else "No link"

        listings.append({
            "title": title,
            "price": price,
            "link": link
        })

        if len(listings) >= 100:
            break

    params["page"] += 1
    time.sleep(2)  # برای جلوگیری از بلاک شدن

print(f"Collected {len(listings)} listings.")

# ذخیره به فایل CSV اگر بخوای
import csv

with open("divar_listings.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["title", "price", "link"])
    writer.writeheader()
    writer.writerows(listings)

Fetching page 1...
No more ads found.
Collected 0 listings.

In [6]:
import requests

url = "https://divar.ir/s/tehran/rent-villa/tehran-zanjan"
params = {
    "districts": "1002,1005,1006,1029,195,196,197,284,312,654,657",
    "map_bbox": "51.33375549316406,35.659141540527344,51.38261413574219,35.70193862915039",
    "map_interaction": "list_only_used",
    "map_place_hash": "1|1001,1002,1005,1006,1029,195,196,197,284,312,654,657|apartment-rent",
    "page": 1
}
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}

response = requests.get(url, params=params, headers=headers)
print(response.status_code)
print(response.url)
print(response.text[:2000])  # فقط 2000 کاراکتر اول HTML را نشان می‌دهد

200
https://divar.ir/s/tehran/rent-villa/tehran-zanjan?districts=1002%2C1005%2C1006%2C1029%2C195%2C196%2C197%2C284%2C312%2C654%2C657&map_bbox=51.33375549316406%2C35.659141540527344%2C51.38261413574219%2C35.70193862915039&map_interaction=list_only_used&map_place_hash=1%7C1001%2C1002%2C1005%2C1006%2C1029%2C195%2C196%2C197%2C284%2C312%2C654%2C657%7Capartment-rent&page=1
<!doctype html>
<html lang="fa-IR" dir="rtl" data-theme="light">
<head>
  <title data-react-helmet="true">رهن و اجاره ویلا، خانه ویلایی و باغ ویلا در زنجان و ۱۱ محلهٔ دیگر تهران - صفحه ۲ | دیوار</title>
  <meta data-react-helmet="true" name="viewport" content="width=992, initial-scale=1"/><meta data-react-helmet="true" name="description" content="بهترین گزینه‌ها برای رهن و اجاره ویلا و خانه‌های ویلایی در زنجان و ۱۱ محلهٔ دیگر تهران را در دیوار پیدا کنید. از امکانات و قیمت‌های متنوع بهره‌مند شوید!"/><meta data-react-helmet="true" name="twitter:card" content="summary"/><meta data-react-helmet="true" name="twitter:site" content="@divar_official"/><meta data-react-helmet="true" name="twitter:url" content="https://divar.ir/s/tehran/rent-villa/tehran-zanjan?districts=1002%2C1005%2C1006%2C1029%2C195%2C196%2C197%2C284%2C312%2C654%2C657&amp;map_bbox=51.33375549316406%2C35.659141540527344%2C51.38261413574219%2C35.70193862915039&amp;map_interaction=list_only_used&amp;map_place_hash=1%7C1001%2C1002%2C1005%2C1006%2C1029%2C195%2C196%2C197%2C284%2C312%2C654%2C657%7Capartment-rent&amp;page=1"/><meta data-react-helmet="true" name="twitter:title" content="رهن و اجاره ویلا، خانه ویلایی و باغ ویلا در زنجان و ۱۱ محلهٔ دیگر تهران - صفحه ۲ | دیوار"/><meta data-react-helmet="true" name="twitter:description" content="بهترین گزینه‌ها برای رهن و اجاره ویلا و خانه‌های ویلایی در زنجان و ۱۱ محلهٔ دیگر تهران را در دیوار پیدا کنید. از امکانات و قیمت‌های متنوع بهره‌مند شوید!"/><meta data-react-helmet="true" name="twitter:image" content="https://s100.divarcdn.com/static/thewall-assets/android-chrome-512x512.png"/><meta data-react-helmet="true" name="twitter:creator" content="سایت دیوار"/><meta data-react-helmet="true" property="og:site_name" content="سایت دیوار"/><meta data-react-helmet="true" property="og:type" content="product"/><meta data-react-helmet="true" property="og:url" content="https://divar.ir/s/tehran/rent-villa/tehran-zanjan?districts=1002%2C1005%2C1006%2C1029%2C195%2C196%2C197%2C284%2C

In [7]:
import requests

def fetch_divar_listings():
    base_url = "https://api.divar.ir/v8/web-search/tehran/rent-villa"
    
    # پارامترهای لینک تو (مناطق و بقیه)
    params = {
        "districts": "1002,1005,1006,1029,195,196,197,284,312,654,657",
        "page": 1
    }
    
    all_listings = []
    
    while len(all_listings) < 100:
        print(f"Fetching page {params['page']}...")
        response = requests.get(base_url, params=params)
        if response.status_code != 200:
            print("خطا در دریافت داده‌ها")
            break
        
        data = response.json()
        
        # چک کن آیا آگهی هست یا نه
        items = data.get("widget_list", [])
        if not items:
            print("دیگه آگهی بیشتری وجود نداره")
            break
        
        # اضافه کردن آگهی‌ها به لیست
        all_listings.extend(items)
        
        # رفتن به صفحه بعد
        params["page"] += 1
    
    # فقط 100 تا آگهی برمی‌گردونیم اگر بیشتر جمع شده باشه
    return all_listings[:100]

if __name__ == "__main__":
    listings = fetch_divar_listings()
    print(f"Collected {len(listings)} listings.")
    for i, listing in enumerate(listings, 1):
        title = listing.get("title", "بدون عنوان")
        price = listing.get("data", {}).get("price", "بدون قیمت")
        print(f"{i}. {title} | قیمت: {price}")

Fetching page 1...
دیگه آگهی بیشتری وجود نداره
Collected 0 listings.

In [8]:
import requests
from bs4 import BeautifulSoup
import time

def scrape_divar_villa_listings(max_pages=5):
    base_url = "https://divar.ir/s/tehran/rent-villa/tehran-zanjan"
    params = {
        "districts": "1002,1005,1006,1029,195,196,197,284,312,654,657",
        "page": 1
    }
    all_listings = []

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
    }

    for page in range(1, max_pages + 1):
        params['page'] = page
        print(f"Fetching page {page}...")
        response = requests.get(base_url, params=params, headers=headers)
        if response.status_code != 200:
            print("خطا در دریافت صفحه")
            break
        
        soup = BeautifulSoup(response.text, "html.parser")
        ads = soup.find_all("div", {"data-testid": "listing-card"})
        if not ads:
            print("دیگه آگهی بیشتری وجود نداره")
            break
        
        for ad in ads:
            title = ad.find("h2")
            price = ad.find("div", {"data-testid": "price"})
            link = ad.find("a", href=True)
            
            all_listings.append({
                "title": title.text.strip() if title else "بدون عنوان",
                "price": price.text.strip() if price else "بدون قیمت",
                "link": "https://divar.ir" + link['href'] if link else "بدون لینک"
            })
        
        time.sleep(1)  # برای کاهش فشار به سرور و جلوگیری از بلاک شدن
    
    return all_listings

if __name__ == "__main__":
    listings = scrape_divar_villa_listings(max_pages=10)
    print(f"Collected {len(listings)} listings.")
    for i, item in enumerate(listings, 1):
        print(f"{i}. {item['title']} | {item['price']} | {item['link']}")

Fetching page 1...
دیگه آگهی بیشتری وجود نداره
Collected 0 listings.

In [11]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
options.add_argument(f"user-agent={user_agent}")

driver = webdriver.Chrome(options=options)

base_url = "https://divar.ir/s/tehran/rent-villa"

all_listings = []

for page in range(1, 10):  # می‌تونی این عدد رو بیشتر کنی برای گرفتن صفحات بیشتر
    print(f"Fetching page {page}...")
    url = f"{base_url}?page={page}"
    driver.get(url)
    time.sleep(5)  # صبر کن تا صفحه کامل لود بشه

    ads = driver.find_elements(By.CSS_SELECTOR, "article.unsafe-kt-post-card")

    if not ads:
        print("دیگه آگهی بیشتری وجود نداره")
        break

    for ad in ads:
        try:
            title = ad.find_element(By.CSS_SELECTOR, "h2.unsafe-kt-post-card__title").text
            price_elems = ad.find_elements(By.CSS_SELECTOR, "div.unsafe-kt-post-card__description")
            deposit = price_elems[0].text if len(price_elems) > 0 else ""
            rent = price_elems[1].text if len(price_elems) > 1 else ""
            location = ad.find_element(By.CSS_SELECTOR, "span.unsafe-kt-post-card__bottom-description").get_attribute("title")
            link = ad.find_element(By.CSS_SELECTOR, "a.unsafe-kt-post-card__action").get_attribute("href")
            if not link.startswith("http"):
                link = "https://divar.ir" + link

            listing = {
                "title": title,
                "location": location,
                "deposit": deposit,
                "rent": rent,
                "link": link
            }
            all_listings.append(listing)
            print(f"{title} | {location} | {deposit} | {rent} | {link}")

        except Exception as e:
            print("خطا در خواندن یک آگهی:", e)

driver.quit()

print(f"\nتعداد کل آگهی‌ها جمع‌آوری شده: {len(all_listings)}")

Fetching page 1...
ویلای ۸۰۰ متری بدون محدودیت مشاغل | کارگزاری املاک پرستیژ نیاوران در باغ فردوس | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۷۵۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C-%DB%B8%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%A8%D8%AF%D9%88%D9%86-%D9%85%D8%AD%D8%AF%D9%88%D8%AF%DB%8C%D8%AA-%D9%85%D8%B4%D8%A7%D8%BA%D9%84/AacM4J7s
۶۰۰ متر در ۵ واحد بر اصلی پالیزی | آژانس توسعه کار آفرین در سیدخندان | ودیعه: ۲۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B6%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D8%AF%D8%B1-%DB%B5-%D9%88%D8%A7%D8%AD%D8%AF-%D8%A8%D8%B1-%D8%A7%D8%B5%D9%84%DB%8C-%D9%BE%D8%A7%D9%84%DB%8C%D8%B2%DB%8C/AarECBAa
180متر اشرفی اصفهانی - برای خوابگاه‌ و سالن زیبایی | ۱ ساعت پیش در المهدی | ودیعه: ۱,۲۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۹۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/180%D9%85%D8%AA%D8%B1-%D8%A7%D8%B4%D8%B1%D9%81%DB%8C-%D8%A7%D8%B5%D9%81%D9%87%D8%A7%D9%86%DB%8C-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%AE%D9%88%D8%A7%D8%A8%DA%AF%D8%A7%D9%87-%D9%88-%D8%B3%D8%A7%D9%84%D9%86-%D8%B2%DB%8C%D8%A8%D8%A7%DB%8C%DB%8C/AarAiDYw
۱۲۳ | ۲ ساعت پیش در نازی‌آباد | ودیعه: ۳۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۹,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B1%DB%B2%DB%B3/Aar0hTSR
۵۰۰ متر ویلایی دربست مناسب مدرسه و خوابگاه | آژانس املاک پایتخت در دروس | ودیعه: ۱۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B5%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D9%85%D8%AF%D8%B1%D8%B3%D9%87-%D9%88-%D8%AE%D9%88%D8%A7%D8%A8%DA%AF%D8%A7%D9%87/wZ3vmGoB
رهن خانه دربستی باغ آذری | ۲ ساعت پیش در باغ آذری | ودیعه: ۳۵۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%AE%D8%A7%D9%86%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D8%A8%D8%A7%D8%BA-%D8%A2%D8%B0%D8%B1%DB%8C/AarYBoz_
اجاره ویلا اداری ۷۰۰ متری ۵ خوابه در شهرک غرب | آژانس املاک دادمان در شهرک غرب | ودیعه: ۱۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱,۲۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%DB%8C%D9%84%D8%A7-%D8%A7%D8%AF%D8%A7%D8%B1%DB%8C-%DB%B7%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8/Aap4dwHL
اجاره خانه ویلایی ( حیاط دار ) در حال بازسازی | در طیب | ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۴,۵۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AD%DB%8C%D8%A7%D8%B7-%D8%AF%D8%A7%D8%B1-%D8%AF%D8%B1-%D8%AD%D8%A7%D9%84-%D8%A8%D8%A7%D8%B2%D8%B3%D8%A7%D8%B2%DB%8C/AaRMVVcS
پیروزی دهم فروردین یاسین (خانه دربستی ۲ونیم طبقه) | املاک مهر در پیروزی | ودیعه: ۱,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۸,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%BE%DB%8C%D8%B1%D9%88%D8%B2%DB%8C-%D8%AF%D9%87%D9%85-%D9%81%D8%B1%D9%88%D8%B1%D8%AF%DB%8C%D9%86-%DB%8C%D8%A7%D8%B3%DB%8C%D9%86-%D8%AE%D8%A7%D9%86%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%DB%B2%D9%88%D9%86%DB%8C%D9%85-%D8%B7%D8%A8%D9%82%D9%87/AabsBtIR
۸۵۰ متر سند اداری ۲۰ پارکینگ فول اداری | آژانس توسعه کار آفرین در ظفر | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۵۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B8%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1-%D8%B3%D9%86%D8%AF-%D8%A7%D8%AF%D8%A7%D8%B1%DB%8C-%DB%B2%DB%B0-%D9%BE%D8%A7%D8%B1%DA%A9%DB%8C%D9%86%DA%AF-%D9%81%D9%88%D9%84-%D8%A7%D8%AF%D8%A7%D8%B1%DB%8C/Aaps-KW8
۷۰۰ متر مستغلات ۹ اتاق ۴ بالکن ۸ پارکینگ | آژانس توسعه کار آفرین در میرداماد | ودیعه: ۲۱,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B7%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%DB%B9-%D8%A7%D8%AA%D8%A7%D9%82-%DB%B4-%D8%A8%D8%A7%D9%84%DA%A9%D9%86-%DB%B8-%D9%BE%D8%A7%D8%B1%DA%A9%DB%8C%D9%86%DA%AF/Aao0nUa9
اجاره خانه ویلایی ۱۳۰ متری ۵ خوابه درسرآسیاب دولاب | ۲ ساعت پیش در سرآسیاب دولاب | ودیعه: ۵۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B3%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1%D8%B3%D8%B1%D8%A2%D8%B3%DB%8C%D8%A7%D8%A8-%D8%AF%D9%88%D9%84%D8%A7%D8%A8/AarYhkAJ
۳۵۰ متر آپارتمان ویلا زردکوه طاهری | آژانس بوتیک املاک ولنجک در زعفرانیه | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B3%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1-%D8%A2%D9%BE%D8%A7%D8%B1%D8%AA%D9%85%D8%A7%D9%86-%D9%88%DB%8C%D9%84%D8%A7-%D8%B2%D8%B1%D8%AF%DA%A9%D9%88%D9%87-%D8%B7%D8%A7%D9%87%D8%B1%DB%8C/AarYRTLb
اجاره اتاق اکوستیک سالیانه یا ماهانه | در باغ خزانه | ودیعه: ۳۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%A7%D8%AA%D8%A7%D9%82-%D8%A7%DA%A9%D9%88%D8%B3%D8%AA%DB%8C%DA%A9-%D8%B3%D8%A7%D9%84%DB%8C%D8%A7%D9%86%D9%87-%DB%8C%D8%A7-%D9%85%D8%A7%D9%87%D8%A7%D9%86%D9%87/AakwZPhH
Fetching page 2...
زعفرانیه ۸۰۰ متر ویلای نوساز | آژانس املاک نیلی فرشته در زعفرانیه | ودیعه: ۳۰,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱,۵۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B2%D8%B9%D9%81%D8%B1%D8%A7%D9%86%DB%8C%D9%87-%DB%B8%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C-%D9%86%D9%88%D8%B3%D8%A7%D8%B2/AaYEsV5z
اجاره خانه ویلایی ۴۰ متری ۳ خوابه در بیسیم | ۳ ساعت پیش در بیسیم | ودیعه: ۳۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۴,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B4%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B3-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%A8%DB%8C%D8%B3%DB%8C%D9%85/AarswwEb
اجاره خانه ویلایی ۴۵۰ متری ۵ خوابه در دروس | آژانس ایرانیان پشتیبانی در دروس | ودیعه: ۱۳,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B4%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%AF%D8%B1%D9%88%D8%B3/wZ9Th4Pe
اجاره خانه ویلایی ۳۰۰ متری ۳ خوابه در تجریش | آژانس املاک زندگی آرمانی در تجریش | ودیعه: ۳,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۳۵۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B3%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B3-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%AA%D8%AC%D8%B1%DB%8C%D8%B4/Aarkghk5
۶۰ متر خونه دربستی در ۲ طبقه . در حال تخلیه | آژانس مشاورین املاک طهرانی در هاشمی | ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۶,۵۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B6%DB%B0-%D9%85%D8%AA%D8%B1-%D8%AE%D9%88%D9%86%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D8%AF%D8%B1-%DB%B2-%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1-%D8%AD%D8%A7%D9%84-%D8%AA%D8%AE%D9%84%DB%8C%D9%87/AargwPIu
خانه دربستی حیاط دار مرکز شهر استفاده تجاری،مسکونی | ۳ ساعت پیش در سلسبیل | ودیعه: ۱,۵۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D8%AD%DB%8C%D8%A7%D8%B7-%D8%AF%D8%A7%D8%B1-%D9%85%D8%B1%DA%A9%D8%B2-%D8%B4%D9%87%D8%B1-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%AA%D8%AC%D8%A7%D8%B1%DB%8C-%D9%85%D8%B3%DA%A9%D9%88%D9%86%DB%8C/AarYg8vg
اجاره واحد مسکونی | ۳ ساعت پیش در افسریه | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۲,۵۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%D8%A7%D8%AD%D8%AF-%D9%85%D8%B3%DA%A9%D9%88%D9%86%DB%8C/Aarcw732
خانه اجاره ای | ۳ ساعت پیش در خواجه نظام الملک | ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۱,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%A7%DB%8C/AarcAsdx
اجاره خانه ویلایی 55متری مستقلات | آژانس مشاورین املاک آنیتا در مقدم | ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-55%D9%85%D8%AA%D8%B1%DB%8C-%D9%85%D8%B3%D8%AA%D9%82%D9%84%D8%A7%D8%AA/Aaqg_VpG
۱طبقه جهت اجاره | ۳ ساعت پیش در مولوی | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B1%D8%B7%D8%A8%D9%82%D9%87-%D8%AC%D9%87%D8%AA-%D8%A7%D8%AC%D8%A7%D8%B1%D9%87/AarUw6FU
امستغلات ۵۰۰ متری روبروی پارک ملت ۱۰ خواب | املاک میداس در جردن | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%DB%B5%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%B1%D9%88%D8%A8%D8%B1%D9%88%DB%8C-%D9%BE%D8%A7%D8%B1%DA%A9-%D9%85%D9%84%D8%AA-%DB%B1%DB%B0-%D8%AE%D9%88%D8%A7%D8%A8/AaFUvDmW
زیرهمکف | آژانس کارشناسان  مسکن محسن در تهرانپارس شرقی | ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۸,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B2%DB%8C%D8%B1%D9%87%D9%85%DA%A9%D9%81/AarUQzkA
اجاره خانه ویلایی ۵۴۵ متری ۵ خوابه در فرمانیه | آژانس آکام در فرمانیه | ودیعه: ۸,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۸۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B5%DB%B4%DB%B5-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D9%81%D8%B1%D9%85%D8%A7%D9%86%DB%8C%D9%87/AarUgc_p
رهن واجاره سوئیت ۴۰متری | ۳ ساعت پیش در مجیدآباد | ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۸,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D9%88%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%B3%D9%88%D8%A6%DB%8C%D8%AA-%DB%B4%DB%B0%D9%85%D8%AA%D8%B1%DB%8C/AarQwcza
خانه ۴۵۰ متر آجری با حیاط بزرگ(انقلاب) | مشاور مجید خماند(مجیدی) در میدان ولیعصر | ودیعه: ۱۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%DB%B4%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1-%D8%A2%D8%AC%D8%B1%DB%8C-%D8%A8%D8%A7-%D8%AD%DB%8C%D8%A7%D8%B7-%D8%A8%D8%B2%D8%B1%DA%AF-%D8%A7%D9%86%D9%82%D9%84%D8%A7%D8%A8/AaY47aC8
ویلایی دو طبقه شمالی دربست | مشاور املاک رحمانی در دولت‌آباد | ودیعه: ۱,۸۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AF%D9%88-%D8%B7%D8%A8%D9%82%D9%87-%D8%B4%D9%85%D8%A7%D9%84%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA/Aaq0_3HZ
۳۰۰متر بنا دربست ۱۰۰متر حیاط مترو تهرانپارس | آژانس املاک  اقدسیه در تهرانپارس غربی | ودیعه: ۱,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۹۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B3%DB%B0%DB%B0%D9%85%D8%AA%D8%B1-%D8%A8%D9%86%D8%A7-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%DB%B1%DB%B0%DB%B0%D9%85%D8%AA%D8%B1-%D8%AD%DB%8C%D8%A7%D8%B7-%D9%85%D8%AA%D8%B1%D9%88-%D8%AA%D9%87%D8%B1%D8%A7%D9%86%D9%BE%D8%A7%D8%B1%D8%B3/Aaq0PZ7b
اجاره کوتاه مدت بلند مدت مجالس لوکیشن فیلم برداری | ۴ ساعت پیش در جماران | ودیعه: ۱,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۳۲۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%DA%A9%D9%88%D8%AA%D8%A7%D9%87-%D9%85%D8%AF%D8%AA-%D8%A8%D9%84%D9%86%D8%AF-%D9%85%D8%AF%D8%AA-%D9%85%D8%AC%D8%A7%D9%84%D8%B3-%D9%84%D9%88%DA%A9%DB%8C%D8%B4%D9%86-%D9%81%DB%8C%D9%84%D9%85-%D8%A8%D8%B1%D8%AF%D8%A7%D8%B1%DB%8C/Aaq0vcSk
خونه ویلایی ۱۱۵متری در۳طبقه و۲سرویس ماشین رو | آژانس قربانی در علی‌آباد | ودیعه: ۱,۳۵۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%AE%D9%88%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B1%DB%B5%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1%DB%B3%D8%B7%D8%A8%D9%82%D9%87-%D9%88%DB%B2%D8%B3%D8%B1%D9%88%DB%8C%D8%B3-%D9%85%D8%A7%D8%B4%DB%8C%D9%86-%D8%B1%D9%88/Aaqwvv8i
ویلایی ۷۷ متری دو طبقه حیاط دار | ۴ ساعت پیش در مینابی | ودیعه: ۷۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B7%DB%B7-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D9%88-%D8%B7%D8%A8%D9%82%D9%87-%D8%AD%DB%8C%D8%A7%D8%B7-%D8%AF%D8%A7%D8%B1/AaqwPPBi
۱۰۰ متر ویلایی ۲ طبقه دربست | آژانس گروه مشاورین املاک کارن در پونک | ودیعه: ۵۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۴۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B1%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B2-%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA/AacIGaNw
منزل دربست فقط خانواده80مترسه ساله کنارگذرامام علی | در سرآسیاب دولاب | ودیعه: ۹۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D9%85%D9%86%D8%B2%D9%84-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%D9%81%D9%82%D8%B7-%D8%AE%D8%A7%D9%86%D9%88%D8%A7%D8%AF%D9%8780%D9%85%D8%AA%D8%B1%D8%B3%D9%87-%D8%B3%D8%A7%D9%84%D9%87-%DA%A9%D9%86%D8%A7%D8%B1%DA%AF%D8%B0%D8%B1%D8%A7%D9%85%D8%A7%D9%85-%D8%B9%D9%84%DB%8C/AaEI74Aw
شهرک غرب۲۸۰متر۴خواب ویلایی۱واحداز۲واحدبا۵۰مترسوئیت | آژانس املاک دادمان در شهرک غرب | ودیعه: ۴,۷۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8%DB%B2%DB%B8%DB%B0%D9%85%D8%AA%D8%B1%DB%B4%D8%AE%D9%88%D8%A7%D8%A8-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C%DB%B1%D9%88%D8%A7%D8%AD%D8%AF%D8%A7%D8%B2%DB%B2%D9%88%D8%A7%D8%AD%D8%AF%D8%A8%D8%A7%DB%B5%DB%B0%D9%85%D8%AA%D8%B1%D8%B3%D9%88%D8%A6%DB%8C%D8%AA/AaqsfSNP
ویلایی ۲ طبقه دربستی موقعیت عالی | در شهرک استقلال | ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B2-%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D9%85%D9%88%D9%82%D8%B9%DB%8C%D8%AA-%D8%B9%D8%A7%D9%84%DB%8C/AafokCMc
Fetching page 3...
ویلای ۱۰۰ متری خلیج فارس | ۴ ساعت پیش در شهرک طالقانی | ودیعه: ۳۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C-%DB%B1%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AE%D9%84%DB%8C%D8%AC-%D9%81%D8%A7%D8%B1%D8%B3/Aaqk_mey
اجاره ویلا ۸۰۰متر ی ۲۰۰ متر بنا قلهک خ دولت | در قلهک | ودیعه: ۳,۵۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%DB%8C%D9%84%D8%A7-%DB%B8%DB%B0%DB%B0%D9%85%D8%AA%D8%B1-%DB%8C-%DB%B2%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D8%A8%D9%86%D8%A7-%D9%82%D9%84%D9%87%DA%A9-%D8%AE-%D8%AF%D9%88%D9%84%D8%AA/AagA3-1t
۷۵ متر خانه دربستی | ۴ ساعت پیش در فلاح | ودیعه: ۷۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B7%DB%B5-%D9%85%D8%AA%D8%B1-%D8%AE%D8%A7%D9%86%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C/Aaqgv544
خانه دربستی تمیز ۵۰ متری یک خواب تمیز | آژانس CNNاعتماد در هاشم‌آباد | ودیعه: ۴۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۲,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D8%AA%D9%85%DB%8C%D8%B2-%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%8C%DA%A9-%D8%AE%D9%88%D8%A7%D8%A8-%D8%AA%D9%85%DB%8C%D8%B2/AakM2Vbm
اجاره خانه ویلایی ۲۷۰ متری ۵ خوابه در پونک | آژانس گروه مشاورین املاک صبح امید در پونک | ودیعه: ۱,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۳۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B2%DB%B7%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D9%BE%D9%88%D9%86%DA%A9/AaqYPhmc
ویلایی در قلب دروس/ قابل تبدیل/ مناسب سکونت ومشاغل | مشاور سارا رضایی  در دروس | ودیعه: ۱۰,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AF%D8%B1-%D9%82%D9%84%D8%A8-%D8%AF%D8%B1%D9%88%D8%B3-%D9%82%D8%A7%D8%A8%D9%84-%D8%AA%D8%A8%D8%AF%DB%8C%D9%84-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D8%B3%DA%A9%D9%88%D9%86%D8%AA-%D9%88%D9%85%D8%B4%D8%A7%D8%BA%D9%84/AabwimRL
خانه ویلایی | ۴ ساعت پیش در طیب | ودیعه: ۴۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۹,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C/AaqYf7uW
۱۰۰ متر/کلنگی/سینا غربی/مترو کمیل/ | آژانس طاها در نواب | ودیعه: ۵۱۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%DB%B1%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%DA%A9%D9%84%D9%86%DA%AF%DB%8C-%D8%B3%DB%8C%D9%86%D8%A7-%D8%BA%D8%B1%D8%A8%DB%8C-%D9%85%D8%AA%D8%B1%D9%88-%DA%A9%D9%85%DB%8C%D9%84/AalgrXYl
اجاره ویلای شیک/ مستغلاتی | زارعی در شهرک غرب | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۶۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C-%D8%B4%DB%8C%DA%A9-%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA%DB%8C/wZzjYHnA
الهیه ۵۵۰ متر ویلایی | مشاور مجیداکبری مبارکه در الهیه | ودیعه: ۲۰,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D9%84%D9%87%DB%8C%D9%87-%DB%B5%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C/AaHAUaOM
ویلا مستغلات ۸۰۰متر بر اصلی | آژانس ماهان زعفرانیه در شهرک غرب | ودیعه: ۱۰,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۶۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7-%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%DB%B8%DB%B0%DB%B0%D9%85%D8%AA%D8%B1-%D8%A8%D8%B1-%D8%A7%D8%B5%D9%84%DB%8C/AafQ3Fm6
۴۰۰ متر ویلایی بهترین لوکیشن شیراز شیخ بهایی ونک | املاک ایران سکنا در ونک | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%DB%B4%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%A8%D9%87%D8%AA%D8%B1%DB%8C%D9%86-%D9%84%D9%88%DA%A9%DB%8C%D8%B4%D9%86-%D8%B4%DB%8C%D8%B1%D8%A7%D8%B2-%D8%B4%DB%8C%D8%AE-%D8%A8%D9%87%D8%A7%DB%8C%DB%8C-%D9%88%D9%86%DA%A9/AaqMfoCy
۸۰۰ متر ویلایی مستقل بازسازی شده ، مناسب سفارتخانه | آژانس املاک خانه ما در امانیه | ودیعه: ۳۰,۰۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%DB%B8%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D9%85%D8%B3%D8%AA%D9%82%D9%84-%D8%A8%D8%A7%D8%B2%D8%B3%D8%A7%D8%B2%DB%8C-%D8%B4%D8%AF%D9%87-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D8%B3%D9%81%D8%A7%D8%B1%D8%AA%D8%AE%D8%A7%D9%86%D9%87/AaY4VCYN
هشترودی 120 متر دو خوابه | مشاور پارسا در اوین | ودیعه: ۲,۵۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D9%87%D8%B4%D8%AA%D8%B1%D9%88%D8%AF%DB%8C-120-%D9%85%D8%AA%D8%B1-%D8%AF%D9%88-%D8%AE%D9%88%D8%A7%D8%A8%D9%87/AaqIvnhY
اجاره خانه ویلایی ۱۰۱۳ متری ۵ خوابه در نیاوران | مشاور مینا ناصری  در نیاوران | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱,۰۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B0%DB%B1%DB%B3-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D9%86%DB%8C%D8%A7%D9%88%D8%B1%D8%A7%D9%86/AaYc4rrH
ویلایی / نوساز / تبدیل رهن و اجاره | مشاور سیروان در شهرک غرب | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۷۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D9%86%D9%88%D8%B3%D8%A7%D8%B2-%D8%AA%D8%A8%D8%AF%DB%8C%D9%84-%D8%B1%D9%87%D9%86-%D9%88-%D8%A7%D8%AC%D8%A7%D8%B1%D9%87/wZrKxw2P
ویلایی / اداری | مشاور سیروان در شهرک غرب | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۳۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%A7%D8%AF%D8%A7%D8%B1%DB%8C/AafQCx4U
ویلایی ۱۷۰ متری ۳ خوابه در شهرک غرب | مشاور آرش جاویدی در شهرک غرب | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۶۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B7%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B3-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8/Aak8TH56
خانه ویلایی ۲۳۰ متری/دروس/سوپر لـ.وکـ.س | آژانس شایگان در دروس | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۹۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B2%DB%B3%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1%D9%88%D8%B3-%D8%B3%D9%88%D9%BE%D8%B1-%D9%84%D9%80-%D9%88%DA%A9%D9%80-%D8%B3/AaN89Dw0
خانه ویلایی دو طبقه شمالی ماشین رو | ۵ ساعت پیش در ابراهیم‌آباد | ودیعه: ۳۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۷,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AF%D9%88-%D8%B7%D8%A8%D9%82%D9%87-%D8%B4%D9%85%D8%A7%D9%84%DB%8C-%D9%85%D8%A7%D8%B4%DB%8C%D9%86-%D8%B1%D9%88/Aaq8eZHT
ساختمان دربست ۳۵۰ متر میدان انقلاب کارگر جنوبی | مشاور امیر بهبهانی در میدان انقلاب | ودیعه: ۱,۲۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۲۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B3%D8%A7%D8%AE%D8%AA%D9%85%D8%A7%D9%86-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%DB%B3%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1-%D9%85%DB%8C%D8%AF%D8%A7%D9%86-%D8%A7%D9%86%D9%82%D9%84%D8%A7%D8%A8-%DA%A9%D8%A7%D8%B1%DA%AF%D8%B1-%D8%AC%D9%86%D9%88%D8%A8%DB%8C/wZwbfzdW
۵۹۰ متر مستغلات / ۸ واحد یکجا | مشاور سامان در صادقیه | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۷۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B5%DB%B9%DB%B0-%D9%85%D8%AA%D8%B1-%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%DB%B8-%D9%88%D8%A7%D8%AD%D8%AF-%DB%8C%DA%A9%D8%AC%D8%A7/AaMMah1w
۵۰مترویلایی۱طبقه دربست/تخلیه/جلیلی | در فلاح | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B5%DB%B0%D9%85%D8%AA%D8%B1%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C%DB%B1%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%D8%AA%D8%AE%D9%84%DB%8C%D9%87-%D8%AC%D9%84%DB%8C%D9%84%DB%8C/Aao8FIGI

In [33]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
options.add_argument(f"user-agent={user_agent}")

driver = webdriver.Chrome(options=options)

base_url = "https://divar.ir/s/tehran/rent-villa"

all_listings = []

for page in range(1, 10):  # می‌تونی این عدد رو بیشتر کنی برای گرفتن صفحات بیشتر
    print(f"Fetching page {page}...")
    url = f"{base_url}?page={page}"
    driver.get(url)
    time.sleep(5)  # صبر کن تا صفحه کامل لود بشه

    ads = driver.find_elements(By.CSS_SELECTOR, "article.unsafe-kt-post-card")

    if not ads:
        print("دیگه آگهی بیشتری وجود نداره")
        break

    for ad in ads:
        try:
            title = ad.find_element(By.CSS_SELECTOR, "h2.unsafe-kt-post-card__title").text
            price_elems = ad.find_elements(By.CSS_SELECTOR, "div.unsafe-kt-post-card__description")
            deposit = price_elems[0].text if len(price_elems) > 0 else ""
            rent = price_elems[1].text if len(price_elems) > 1 else ""
            location = ad.find_element(By.CSS_SELECTOR, "span.unsafe-kt-post-card__bottom-description").get_attribute("title")
            link = ad.find_element(By.CSS_SELECTOR, "a.unsafe-kt-post-card__action").get_attribute("href")
            if not link.startswith("http"):
                link = "https://divar.ir" + link

            listing = {
                "title": title,
                "location": location,
                "deposit": deposit,
                "rent": rent,
                "link": link
            }
            all_listings.append(listing)
            print(f"{title} | {location} | {deposit} | {rent} | {link}")

        except Exception as e:
            print("خطا در خواندن یک آگهی:", e)

driver.quit()

print(f"\nتعداد کل آگهی‌ها جمع‌آوری شده: {len(all_listings)}")

Fetching page 1...
ملک دربست جهت اداری ،آموزشی، درمانی | آژانس املاک روشن در شهرک راه‌آهن | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%85%D9%84%DA%A9-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%D8%AC%D9%87%D8%AA-%D8%A7%D8%AF%D8%A7%D8%B1%DB%8C-%D8%A2%D9%85%D9%88%D8%B2%D8%B4%DB%8C-%D8%AF%D8%B1%D9%85%D8%A7%D9%86%DB%8C/AaqQP7Zu
اجاره خانه ویلایی ۵۰ متری در طیب | در طیب | ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۶,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1-%D8%B7%DB%8C%D8%A8/AagY7fyz
اجاره حیاط دربستی ۵۶ متر یک طبقه روبرو مترو رضایی | در شوش | ودیعه: ۳۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AD%DB%8C%D8%A7%D8%B7-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%DB%B5%DB%B6-%D9%85%D8%AA%D8%B1-%DB%8C%DA%A9-%D8%B7%D8%A8%D9%82%D9%87-%D8%B1%D9%88%D8%A8%D8%B1%D9%88-%D9%85%D8%AA%D8%B1%D9%88-%D8%B1%D8%B6%D8%A7%DB%8C%DB%8C/AaiMPpQ9
خانه ۱۰۰ متری سه واحد | در شوش | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%DB%B1%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%B3%D9%87-%D9%88%D8%A7%D8%AD%D8%AF/Aab0qE9A
67 متری کلنگی دربستی مناسب انبار و تولیدی | مشاورین املاک بزرگ برج در ظهیرآباد | ودیعه: ۳۵۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/67-%D9%85%D8%AA%D8%B1%DB%8C-%DA%A9%D9%84%D9%86%DA%AF%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D8%A7%D9%86%D8%A8%D8%A7%D8%B1-%D9%88-%D8%AA%D9%88%D9%84%DB%8C%D8%AF%DB%8C/Aaa8Y4hW
حیاط دربست ۲طبقه بازسازی شد استادمعین | مسکن آذری در استاد معین | ودیعه: ۳,۰۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%AD%DB%8C%D8%A7%D8%B7-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%DB%B2%D8%B7%D8%A8%D9%82%D9%87-%D8%A8%D8%A7%D8%B2%D8%B3%D8%A7%D8%B2%DB%8C-%D8%B4%D8%AF-%D8%A7%D8%B3%D8%AA%D8%A7%D8%AF%D9%85%D8%B9%DB%8C%D9%86/AaqIQU1N
خانه ویلای دوطبقه و نیم | مشاور بهروز در علی‌آباد | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۴,۵۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C-%D8%AF%D9%88%D8%B7%D8%A8%D9%82%D9%87-%D9%88-%D9%86%DB%8C%D9%85/AarMUYtl
ملک دربستی مناسب سکونت و کار زاهدگیلانی | آژانس املاک دیوار در پیروزی | ودیعه: ۱,۲۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D9%85%D9%84%DA%A9-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D8%B3%DA%A9%D9%88%D9%86%D8%AA-%D9%88-%DA%A9%D8%A7%D8%B1-%D8%B2%D8%A7%D9%87%D8%AF%DA%AF%DB%8C%D9%84%D8%A7%D9%86%DB%8C/AarI07gb
رهن واجاره خانه ویلایی دوطبقه در دولت آباد | ۱ ساعت پیش در شهادت | ودیعه: ۵۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D9%88%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AF%D9%88%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1-%D8%AF%D9%88%D9%84%D8%AA-%D8%A2%D8%A8%D8%A7%D8%AF/AarIkg_W
خانه ویلایی ۳۰۰ متری دوبلکس پارکینگ دار خ بهبودی | مشاور هاشمی خط جدید در توحید | ودیعه: ۱,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۷۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B3%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D9%88%D8%A8%D9%84%DA%A9%D8%B3-%D9%BE%D8%A7%D8%B1%DA%A9%DB%8C%D9%86%DA%AF-%D8%AF%D8%A7%D8%B1-%D8%AE-%D8%A8%D9%87%D8%A8%D9%88%D8%AF%DB%8C/AaUEuHqZ
ویلایی ۲۵۰متری /دوبلکس/فرخی/بازسازی شده | آژانس  املاک ایوان در پاسداران | ودیعه: ۶,۰۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B2%DB%B5%DB%B0%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D9%88%D8%A8%D9%84%DA%A9%D8%B3-%D9%81%D8%B1%D8%AE%DB%8C-%D8%A8%D8%A7%D8%B2%D8%B3%D8%A7%D8%B2%DB%8C-%D8%B4%D8%AF%D9%87/AaPsC2lw
رهن خانه ویلایی ۴۲ متری دوطبقه در شهرک طالقانی | ۱ ساعت پیش در شهرک طالقانی | ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B4%DB%B2-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D9%88%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%B7%D8%A7%D9%84%D9%82%D8%A7%D9%86%DB%8C/AarIklIw
اجاره خانه ویلایی | ۱ ساعت پیش در اتابک | ودیعه: ۹۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C/AarI0bd0
اجاره ویلایی شهرک غرب ۳۰۰متر/۴ خواب/حیاط در اختیار | آژانس املاک ‌وی آی پی در شهرک غرب | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۵۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8-%DB%B3%DB%B0%DB%B0%D9%85%D8%AA%D8%B1-%DB%B4-%D8%AE%D9%88%D8%A7%D8%A8-%D8%AD%DB%8C%D8%A7%D8%B7-%D8%AF%D8%B1-%D8%A7%D8%AE%D8%AA%DB%8C%D8%A7%D8%B1/AarEkD5d
Fetching page 2...
اجاره خانه ویلایی ۲۹۰ متری ۵ خوابه در ائمه اطهار | ۱ ساعت پیش در ائمه اطهار | ودیعه: ۱,۵۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B2%DB%B9%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%A7%D8%A6%D9%85%D9%87-%D8%A7%D8%B7%D9%87%D8%A7%D8%B1/Aar4D8ri
دربست ۲ طبقه بازسازی شده شهرک فردوس | ۱ ساعت پیش در شهرک فردوس | ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۲,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%DB%B2-%D8%B7%D8%A8%D9%82%D9%87-%D8%A8%D8%A7%D8%B2%D8%B3%D8%A7%D8%B2%DB%8C-%D8%B4%D8%AF%D9%87-%D8%B4%D9%87%D8%B1%DA%A9-%D9%81%D8%B1%D8%AF%D9%88%D8%B3/Aar4jZOQ
۶۵۰متر۱۲ اتاق۳طبقه شمالی حیاط مشجر شهرک راه اهن | املاک بزرگ آساز در شهرک راه‌آهن | ودیعه: ۴,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۷۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B6%DB%B5%DB%B0%D9%85%D8%AA%D8%B1%DB%B1%DB%B2-%D8%A7%D8%AA%D8%A7%D9%82%DB%B3%D8%B7%D8%A8%D9%82%D9%87-%D8%B4%D9%85%D8%A7%D9%84%DB%8C-%D8%AD%DB%8C%D8%A7%D8%B7-%D9%85%D8%B4%D8%AC%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%B1%D8%A7%D9%87-%D8%A7%D9%87%D9%86/Aar4Te2m
۶۰ متر ۲ طبقه دربستی در حیدری شمالی | ۱ ساعت پیش در شهرک ولیعصر | ودیعه: ۵۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۴,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B6%DB%B0-%D9%85%D8%AA%D8%B1-%DB%B2-%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D8%AF%D8%B1-%D8%AD%DB%8C%D8%AF%D8%B1%DB%8C-%D8%B4%D9%85%D8%A7%D9%84%DB%8C/AajcmueK
ویلا تریبلکس استخر دار جاده چالوس مبله | ۲ ساعت پیش در ولنجک | ودیعه: ۲,۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7-%D8%AA%D8%B1%DB%8C%D8%A8%D9%84%DA%A9%D8%B3-%D8%A7%D8%B3%D8%AA%D8%AE%D8%B1-%D8%AF%D8%A7%D8%B1-%D8%AC%D8%A7%D8%AF%D9%87-%DA%86%D8%A7%D9%84%D9%88%D8%B3-%D9%85%D8%A8%D9%84%D9%87/Aar0jh7Y
۲۴۰ متر ویلایی شهرک غرب رهن کانل | ۲ ساعت پیش در شهرک غرب | ودیعه: ۶,۰۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%DB%B2%DB%B4%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8-%D8%B1%D9%87%D9%86-%DA%A9%D8%A7%D9%86%D9%84/AarwzFz-
اجاره خانه ویلایی ۳۰۰ متری ۴ خوابه در شهرک غرب | مشاورین املاک استیلا در شهرک غرب | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۸۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B3%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B4-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8/Aai4yrbN
اجاره خانه ویلایی ۷۵۰ متری ۱۲خوابه در کامرانیه | مشاور آقای مهدی اسماعیلی در کامرانیه | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۴۵۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B7%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B1%DB%B2%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%DA%A9%D8%A7%D9%85%D8%B1%D8%A7%D9%86%DB%8C%D9%87/AarszLRP
خانه ویلایی دربستی ۱۶۵ متر ۳ طبقه ۳ سرویس کامل | ۲ ساعت پیش در جی | ودیعه: ۸۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۲,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%DB%B1%DB%B6%DB%B5-%D9%85%D8%AA%D8%B1-%DB%B3-%D8%B7%D8%A8%D9%82%D9%87-%DB%B3-%D8%B3%D8%B1%D9%88%DB%8C%D8%B3-%DA%A9%D8%A7%D9%85%D9%84/AaowUY0g
اجاره اتاق | ۲ ساعت پیش در خاوران | ودیعه: ۱۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۳,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%A7%D8%AA%D8%A7%D9%82/AaroTtKn
شهرک غرب ۸۰۰ متر ویلایی رهن و اجاره | آژانس املاک دادمان در شهرک غرب | ودیعه: ۱۰,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۷۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8-%DB%B8%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%B1%D9%87%D9%86-%D9%88-%D8%A7%D8%AC%D8%A7%D8%B1%D9%87/AacokXGZ
اجاره واحد منزل | ۲ ساعت پیش در شهرک آزادی | ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۹,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%D8%A7%D8%AD%D8%AF-%D9%85%D9%86%D8%B2%D9%84/AaqIffeL
اجاره خانه ویلایی ۱۸۰ متری ۳ خوابه / پل سیمان | مشاور کریمی در منصوریه (پل سیمان) | ودیعه: ۱,۲۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B8%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B3-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D9%BE%D9%84-%D8%B3%DB%8C%D9%85%D8%A7%D9%86/AaU0bcNH
67متری دربستی مناسب اتباع و تولیدی و انبار | مشاورین املاک بزرگ برج در ظهیرآباد | ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/67%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D8%A7%D8%AA%D8%A8%D8%A7%D8%B9-%D9%88-%D8%AA%D9%88%D9%84%DB%8C%D8%AF%DB%8C-%D9%88-%D8%A7%D9%86%D8%A8%D8%A7%D8%B1/Aapk_Plq
Fetching page 3...
رهن خانه ویلایی ۴۰ متری در مقدم | ۲ ساعت پیش در مقدم | ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B4%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1-%D9%85%D9%82%D8%AF%D9%85/AarADKmM
ویلایی ۴۰ متری / دو طبقه /در هاشمی پارکینگ موتور | آژانس سناتور در زنجان | ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۶,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B4%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D9%88-%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%DB%8C-%D9%BE%D8%A7%D8%B1%DA%A9%DB%8C%D9%86%DA%AF-%D9%85%D9%88%D8%AA%D9%88%D8%B1/AajskhxL
۲۸۰ متر کلنگی دربستی.پونک.سردارجنگل | مسکن دانیال در پونک | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%DB%B2%DB%B8%DB%B0-%D9%85%D8%AA%D8%B1-%DA%A9%D9%84%D9%86%DA%AF%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D9%BE%D9%88%D9%86%DA%A9-%D8%B3%D8%B1%D8%AF%D8%A7%D8%B1%D8%AC%D9%86%DA%AF%D9%84/AaokUNRu
دربستی | ۳ ساعت پیش در گلچین | ودیعه: ۶۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C/Aar0ys51
اجاره 3 طبقه دربستی شیک، فلاح، سجاد شمالی | مشاور عزت سمیعی در طوس | ودیعه: ۱,۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-3-%D8%B7%D8%A8%D9%82%D9%87-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%D8%B4%DB%8C%DA%A9-%D9%81%D9%84%D8%A7%D8%AD-%D8%B3%D8%AC%D8%A7%D8%AF-%D8%B4%D9%85%D8%A7%D9%84%DB%8C/AarwS1Tm
اجاره خانه ویلایی دربست حیاط دار | در عبدل‌آباد | ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۲,۵۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%D8%AD%DB%8C%D8%A7%D8%B7-%D8%AF%D8%A7%D8%B1/AamsdYkj
خانه ویلایی ۵۰ متری ۳ طبقه تک سرویس | ۳ ساعت پیش در شوش | ودیعه: ۵۵۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B3-%D8%B7%D8%A8%D9%82%D9%87-%D8%AA%DA%A9-%D8%B3%D8%B1%D9%88%DB%8C%D8%B3/Aaroiy0n
رهن عمارت قاجاری 480 متری در کـاشــان | ۳ ساعت پیش در پاسداران | ودیعه: ۹۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۲,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%B9%D9%85%D8%A7%D8%B1%D8%AA-%D9%82%D8%A7%D8%AC%D8%A7%D8%B1%DB%8C-480-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1-%DA%A9%D9%80%D8%A7%D8%B4%D9%80%D9%80%D8%A7%D9%86/AaroykIO
اجاره واحد مستقل ۱۲۵ متری ۱ خوابه در شهرک شریعتی | در شهرک شریعتی | ودیعه: ۹۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۹,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%D8%A7%D8%AD%D8%AF-%D9%85%D8%B3%D8%AA%D9%82%D9%84-%DB%B1%DB%B2%DB%B5-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B1-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%B4%D8%B1%DB%8C%D8%B9%D8%AA%DB%8C/AaVIO3gX
اجاره خانه ویلایی ۹۰۰ متری ۵ خوابه در شهرک غرب | مشاور فدایی در شهرک غرب | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۵۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B9%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8/wZw7PP6J
اجاره خانه ویلایی ۸۰۰ متری ۵ خوابه در شهرک غرب | مشاور احمدهاشمی در ایوانک | ودیعه: ۱۷,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B8%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D8%BA%D8%B1%D8%A8/Aab8hIRD
اجاره ویلایی ۴۰۰متر نیاوران/معماری خاص | در نیاوران | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۵۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B4%DB%B0%DB%B0%D9%85%D8%AA%D8%B1-%D9%86%DB%8C%D8%A7%D9%88%D8%B1%D8%A7%D9%86-%D9%85%D8%B9%D9%85%D8%A7%D8%B1%DB%8C-%D8%AE%D8%A7%D8%B5/AaQQt10B
اجاره خانه ویلایی در ابوذر (منطقه ۱۵) | ۳ ساعت پیش در ابوذر (منطقه ۱۵) | ودیعه: ۲۵۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%AF%D8%B1-%D8%A7%D8%A8%D9%88%D8%B0%D8%B1-%D9%85%D9%86%D8%B7%D9%82%D9%87-%DB%B1%DB%B5/AarUS86C
اجاره اپارتمان دربستی ۱۵۰ متری ، دو نیم طبقه مستقل | آژانس املاک شاهان در استاد معین | ودیعه: ۸۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%A7%D9%BE%D8%A7%D8%B1%D8%AA%D9%85%D8%A7%D9%86-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA%DB%8C-%DB%B1%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D9%88-%D9%86%DB%8C%D9%85-%D8%B7%D8%A8%D9%82%D9%87-%D9%85%D8%B3%D8%AA%D9%82%D9%84/Aai8e24s
Fetching page 4...
۸۵۰ متر سند اداری ۲۰ پارکینگ فول اداری | آژانس توسعه کار آفرین در ظفر | ودیعه: ۵,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۵۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B8%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1-%D8%B3%D9%86%D8%AF-%D8%A7%D8%AF%D8%A7%D8%B1%DB%8C-%DB%B2%DB%B0-%D9%BE%D8%A7%D8%B1%DA%A9%DB%8C%D9%86%DA%AF-%D9%81%D9%88%D9%84-%D8%A7%D8%AF%D8%A7%D8%B1%DB%8C/Aaps-KW8
۷۰۰ متر مستغلات ۹ اتاق ۴ بالکن ۸ پارکینگ | آژانس توسعه کار آفرین در میرداماد | ودیعه: ۲۱,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B7%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%DB%B9-%D8%A7%D8%AA%D8%A7%D9%82-%DB%B4-%D8%A8%D8%A7%D9%84%DA%A9%D9%86-%DB%B8-%D9%BE%D8%A7%D8%B1%DA%A9%DB%8C%D9%86%DA%AF/Aao0nUa9
اجاره خانه ویلایی ۱۳۰ متری ۵ خوابه درسرآسیاب دولاب | ۴ ساعت پیش در سرآسیاب دولاب | ودیعه: ۵۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B3%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B5-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1%D8%B3%D8%B1%D8%A2%D8%B3%DB%8C%D8%A7%D8%A8-%D8%AF%D9%88%D9%84%D8%A7%D8%A8/AarYhkAJ
۳۵۰ متر آپارتمان ویلا زردکوه طاهری | آژانس بوتیک املاک ولنجک در زعفرانیه | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B3%DB%B5%DB%B0-%D9%85%D8%AA%D8%B1-%D8%A2%D9%BE%D8%A7%D8%B1%D8%AA%D9%85%D8%A7%D9%86-%D9%88%DB%8C%D9%84%D8%A7-%D8%B2%D8%B1%D8%AF%DA%A9%D9%88%D9%87-%D8%B7%D8%A7%D9%87%D8%B1%DB%8C/AarYRTLb
اجاره اتاق اکوستیک سالیانه یا ماهانه | در باغ خزانه | ودیعه: ۲۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%A7%D8%AA%D8%A7%D9%82-%D8%A7%DA%A9%D9%88%D8%B3%D8%AA%DB%8C%DA%A9-%D8%B3%D8%A7%D9%84%DB%8C%D8%A7%D9%86%D9%87-%DB%8C%D8%A7-%D9%85%D8%A7%D9%87%D8%A7%D9%86%D9%87/AakwZPhH
فرمانیه براصلی/۱۱۰۰ متر بنا ۳ طبقه/مناسب مدرسه و.. | مشاور مسعود در فرمانیه | ودیعه: ۳۰,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۶۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%81%D8%B1%D9%85%D8%A7%D9%86%DB%8C%D9%87-%D8%A8%D8%B1%D8%A7%D8%B5%D9%84%DB%8C-%DB%B1%DB%B1%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D8%A8%D9%86%D8%A7-%DB%B3-%D8%B7%D8%A8%D9%82%D9%87-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D9%85%D8%AF%D8%B1%D8%B3%D9%87-%D9%88/AaXsWqWf
مناسب مدرسه/خوابگاه/شرکت‌های برند | املاک بزرگ پاشا در سهروردی | ودیعه: ۱۳,۵۰۰,۰۰۰,۰۰۰ تومان | رهن کامل | https://divar.ir/v/%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D9%85%D8%AF%D8%B1%D8%B3%D9%87-%D8%AE%D9%88%D8%A7%D8%A8%DA%AF%D8%A7%D9%87-%D8%B4%D8%B1%DA%A9%D8%AA-%D9%87%D8%A7%DB%8C-%D8%A8%D8%B1%D9%86%D8%AF/AarUxAGX
اجاره خانه ویلایی ۶۵ متری ۱ خوابه در امین حضور | در امین حضور | ودیعه: ۳۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9%87-%D8%AE%D8%A7%D9%86%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%DB%B6%DB%B5-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B1-%D8%AE%D9%88%D8%A7%D8%A8%D9%87-%D8%AF%D8%B1-%D8%A7%D9%85%DB%8C%D9%86-%D8%AD%D8%B6%D9%88%D8%B1/AaZY_OpP
خوابگاه اقامتگاه پانسیون آقایان وصال شیرازی | در دانشگاه تهران | ودیعه: ۱,۰۰۰,۰۰۰ تومان | اجاره: ۴,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%AE%D9%88%D8%A7%D8%A8%DA%AF%D8%A7%D9%87-%D8%A7%D9%82%D8%A7%D9%85%D8%AA%DA%AF%D8%A7%D9%87-%D9%BE%D8%A7%D9%86%D8%B3%DB%8C%D9%88%D9%86-%D8%A2%D9%82%D8%A7%DB%8C%D8%A7%D9%86-%D9%88%D8%B5%D8%A7%D9%84-%D8%B4%DB%8C%D8%B1%D8%A7%D8%B2%DB%8C/wZkFxEK1
فرشته ویلایی سوپر لوکس مناسب تمامی مشاغل | آژانس پرستیژ در الهیه | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۹۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%81%D8%B1%D8%B4%D8%AA%D9%87-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D8%B3%D9%88%D9%BE%D8%B1-%D9%84%D9%88%DA%A9%D8%B3-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D8%AA%D9%85%D8%A7%D9%85%DB%8C-%D9%85%D8%B4%D8%A7%D8%BA%D9%84/Aar8wPqU
منزل ویلایی(میدان آزادی)رهن واجاره | ۵ ساعت پیش در استاد معین | ودیعه: ۳۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۴,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%85%D9%86%D8%B2%D9%84-%D9%88%DB%8C%D9%84%D8%A7%DB%8C%DB%8C-%D9%85%DB%8C%D8%AF%D8%A7%D9%86-%D8%A2%D8%B2%D8%A7%D8%AF%DB%8C-%D8%B1%D9%87%D9%86-%D9%88%D8%A7%D8%AC%D8%A7%D8%B1%D9%87/Aar0gCMu
ویلا مستغلات مناسب‌ کار در اقدسیه | آژانس کلید در اقدسیه | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۳۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D9%88%DB%8C%D9%84%D8%A7-%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%DA%A9%D8%A7%D8%B1-%D8%AF%D8%B1-%D8%A7%D9%82%D8%AF%D8%B3%DB%8C%D9%87/AaS0CYew
۶۰۰ متر ویلا مستقل/تراس و حیاط قابل چیدمان | مسکن آبان فرمانیه در فرمانیه | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۵۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B6%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1-%D9%88%DB%8C%D9%84%D8%A7-%D9%85%D8%B3%D8%AA%D9%82%D9%84-%D8%AA%D8%B1%D8%A7%D8%B3-%D9%88-%D8%AD%DB%8C%D8%A7%D8%B7-%D9%82%D8%A7%D8%A8%D9%84-%DA%86%DB%8C%D8%AF%D9%85%D8%A7%D9%86/AaYcKoGs
اپارتمان ۶۴ متری ، ۲ خواب ، طبقه اول | ۵ ساعت پیش در اسکندری | ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۱۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D9%BE%D8%A7%D8%B1%D8%AA%D9%85%D8%A7%D9%86-%DB%B6%DB%B4-%D9%85%D8%AA%D8%B1%DB%8C-%DB%B2-%D8%AE%D9%88%D8%A7%D8%A8-%D8%B7%D8%A8%D9%82%D9%87-%D8%A7%D9%88%D9%84/Aar0AEUf
Fetching page 5...
۱طبقه جهت اجاره | ۵ ساعت پیش در مولوی | ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۵,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%DB%B1%D8%B7%D8%A8%D9%82%D9%87-%D8%AC%D9%87%D8%AA-%D8%A7%D8%AC%D8%A7%D8%B1%D9%87/AarUw6FU
امستغلات ۵۰۰ متری روبروی پارک ملت ۱۰ خواب | املاک میداس در جردن | ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۲۰۰,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%A7%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%DB%B5%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%B1%D9%88%D8%A8%D8%B1%D9%88%DB%8C-%D9%BE%D8%A7%D8%B1%DA%A9-%D9%85%D9%84%D8%AA-%DB%B1%DB%B0-%D8%AE%D9%88%D8%A7%D8%A8/AaFUvDmW
زیرهمکف | آژانس کارشناسان  مسکن محسن در تهرانپارس شرقی | ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان | اجاره: ۸,۰۰۰,۰۰۰ تومان | https://divar.ir/v/%D8%B2%DB%8C%D8%B1%D9%87%D9%85%DA%A9%D9%81/AarUQzkA

In [34]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time
import pandas as pd

options = Options()
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
options.add_argument(f"user-agent={user_agent}")
options.add_argument("--headless")  # بدون باز شدن پنجره مرورگر

driver = webdriver.Chrome(options=options)

base_url = "https://divar.ir/s/tehran/rent-villa"
all_listings = []

for page in range(1, 10):  # گرفتن ۹ صفحه
    print(f"Fetching page {page}...")
    url = f"{base_url}?page={page}"
    driver.get(url)
    time.sleep(5)  # صبر برای لود کامل صفحه

    ads = driver.find_elements(By.CSS_SELECTOR, "article.unsafe-kt-post-card")
    if not ads:
        print("دیگه آگهی بیشتری وجود نداره")
        break

    for ad in ads:
        try:
            title = ad.find_element(By.CSS_SELECTOR, "h2.unsafe-kt-post-card__title").text
            price_elems = ad.find_elements(By.CSS_SELECTOR, "div.unsafe-kt-post-card__description")
            deposit = price_elems[0].text if len(price_elems) > 0 else ""
            rent = price_elems[1].text if len(price_elems) > 1 else ""
            location = ad.find_element(By.CSS_SELECTOR, "span.unsafe-kt-post-card__bottom-description").get_attribute("title")
            link = ad.find_element(By.CSS_SELECTOR, "a.unsafe-kt-post-card__action").get_attribute("href")
            if not link.startswith("http"):
                link = "https://divar.ir" + link

            listing = {
                "title": title,
                "location": location,
                "deposit": deposit,
                "rent": rent,
                "link": link
            }
            all_listings.append(listing)
        except Exception as e:
            print("خطا در خواندن یک آگهی:", e)

driver.quit()

# ذخیره در CSV
df = pd.DataFrame(all_listings)
df.to_csv("divar_listings.csv", index=False)
print(f"\nتعداد کل آگهی‌ها جمع‌آوری شده: {len(df)}")

Fetching page 1...
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
Fetching page 6...
Fetching page 7...
Fetching page 8...
Fetching page 9...

تعداد کل آگهی‌ها جمع‌آوری شده: 126

In [36]:
import pandas as pd

# پس از گرفتن داده‌ها:
df = pd.DataFrame(all_listings)

# نمایش جدول در همان سلول
df

,title,location,deposit,rent,link
0,اجاره خانه ویلایی ۵۵ متری ۱ خوابه در خاک سفید,۱ ساعت پیش در خاک سفید,"ودیعه: ۱۵۰,۰۰۰,۰۰۰ تومان","اجاره: ۱۴,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9...
1,3طبقه قابل سکونت خیابان اردشیر,۱ ساعت پیش در آذری,"ودیعه: ۹۰۰,۰۰۰,۰۰۰ تومان",رهن کامل,https://divar.ir/v/3%D8%B7%D8%A8%D9%82%D9%87-%...
2,چهار طبقه/یکجا/لوکیشن عالی,۱ ساعت پیش در تهران‌نو,"ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۷۵,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%DA%86%D9%87%D8%A7%D8%B1-%D...
3,اجاره خانه ویلایی ۸۰ متری ۳ خوابه در شهرک طالقانی,در شهرک طالقانی,"ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۳,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9...
4,اجاره خانه ویلایی ۳۰۰ متری ۴ خوابه جهانتاب,آژانس املاک یارا پاسداران در اختیاریه,"ودیعه: ۲,۰۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۱۶۰,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%A7%D8%AC%D8%A7%D8%B1%D9...
...,...,...,...,...,...
121,اتاق ۱۰متری مجردی برای یک نفر آقا,در مولوی,"ودیعه: ۱۲,۰۰۰,۰۰۰ تومان","اجاره: ۴,۵۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%A7%D8%AA%D8%A7%D9%82-%D...
122,آپارتمان۵۰متر دو خواب,آژانس املاک دریا در هاشمی,"ودیعه: ۱۵۰,۰۰۰,۰۰۰ تومان","اجاره: ۱۰,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%A2%D9%BE%D8%A7%D8%B1%D8...
123,خانه دربست ۲ طبقه ده ونک,آژانس احسان در ده‌ونک,"ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۶۸,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D...
124,مستغلات ، چهار طبقه جنوبی,املاک میداس در جردن,"ودیعه: ۷,۰۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۳۵۰,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D9%85%D8%B3%D8%AA%D8%BA%D9...
125,رهن خانه ویلایی ۱۵۰ متری ۳ خوابه در شریف,۱۰ ساعت پیش در شریف,"ودیعه: ۴,۰۰۰,۰۰۰,۰۰۰ تومان",رهن کامل,https://divar.ir/v/%D8%B1%D9%87%D9%86-%D8%AE%D...

In [39]:
import pandas as pd

# فرض: all_listings همون لیست آگهی‌های خامه
df = pd.DataFrame(all_listings)

# حذف ردیف‌هایی که location ندارن (اختیاری ولی مفید)
df = df.dropna(subset=['location'])

# تعریف مناطق مد نظر
target_areas = ["هاشمی", "بریانک", "جی", "جیحون", "سلسبیل", "سلیمانی", "نواب", "هفت چنار"]

# فیلتر کردن مناطق
filtered_df = df[df['location'].apply(lambda loc: any(area in loc for area in target_areas))]

# نمایش نتایج فیلتر شده
filtered_df

,title,location,deposit,rent,link
57,۶۰ متر خونه دربستی در ۲ طبقه . در حال تخلیه,آژانس مشاورین املاک طهرانی در هاشمی,"ودیعه: ۴۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۶,۵۰۰,۰۰۰ تومان",https://divar.ir/v/%DB%B6%DB%B0-%D9%85%D8%AA%D...
58,خانه دربستی حیاط دار مرکز شهر استفاده تجاری،مس...,۶ ساعت پیش در سلسبیل,"ودیعه: ۱,۵۰۰,۰۰۰,۰۰۰ تومان",رهن کامل,https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D...
66,رهن واجاره سوئیت ۴۰متری,۶ ساعت پیش در مجیدآباد,"ودیعه: ۱۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۸,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%B1%D9%87%D9%86-%D9%88%D...
67,خانه ۴۵۰ متر آجری با حیاط بزرگ(انقلاب),مشاور مجید خماند(مجیدی) در میدان ولیعصر,"ودیعه: ۱۲,۰۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۱۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%AE%D8%A7%D9%86%D9%87-%D...
74,۱۰۰ متر/کلنگی/سینا غربی/مترو کمیل/,آژانس طاها در نواب,"ودیعه: ۵۱۰,۰۰۰,۰۰۰ تومان",رهن کامل,https://divar.ir/v/%DB%B1%DB%B0%DB%B0-%D9%85%D...
76,الهیه ۵۵۰ متر ویلایی,مشاور مجیداکبری مبارکه در الهیه,"ودیعه: ۲۰,۰۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۱۰,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%A7%D9%84%D9%87%DB%8C%D9...
104,۲طبقه دربست ۵۰ متری سرویس کامل مرتضوی جیحون,مسکن بزرگ فدک در جیحون,"ودیعه: ۵۷۰,۰۰۰,۰۰۰ تومان",رهن کامل,https://divar.ir/v/%DB%B2%D8%B7%D8%A8%D9%82%D9...
105,100متر،خانه ویلایی قصرالدشت مرتضوی,آژانس دکتر ملک املاک جوان در جیحون,"ودیعه: ۲۰۰,۰۰۰,۰۰۰ تومان","اجاره: ۲۵,۰۰۰,۰۰۰ تومان",https://divar.ir/v/100%D9%85%D8%AA%D8%B1-%D8%A...
122,آپارتمان۵۰متر دو خواب,آژانس املاک دریا در هاشمی,"ودیعه: ۱۵۰,۰۰۰,۰۰۰ تومان","اجاره: ۱۰,۰۰۰,۰۰۰ تومان",https://divar.ir/v/%D8%A2%D9%BE%D8%A7%D8%B1%D8...