AI Automation for Real State
Posted 1 hour ago
Worldwide
Specialized profiles can help you better highlight your expertise when submitting proposals to jobs like these. Create a specialized profile.

Summary
Summary
We are currently seeking a talented freelancer to join our team and assist us in AI Automation

This role requires someone who is skilled in AI Data Analysis - AI Chatbot - AI Automated Social Media

The ideal candidate will be able to [TASKS/RESPONSIBILITIES).

Responsibilities:

Collaborate with our team to develop and execute effective strategies for AI Automation.

Utilize your expertise in AI Automation to deliver high-quality results.

Communicate regularly with the team to provide updates and discuss project progress.

Meet deadlines and ensure all tasks are completed accurately and efficiently.
Requirements:

Proven experience in  with a strong portfolio of past work.

Proficiency in AI Data Analysis - AI Chatbot - AI Automated Social Media

Excellent communication and collaboration skills.

Ability to work independently and as part of a team.

Attention to detail and a commitment to delivering exceptional results.

In [ ]:
!pip install requests beautifulsoup4 pandas matplotlib seaborn scikit-learn

In [ ]:
!pip install selenium webdriver-manager

In [11]:
import requests
import pandas as pd

# URL of the Divar API for rent apartments in Tehran
url = "https://api.divar.ir/v8/web-search/tehran/rent-apartment "

# Send a GET request to the API
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    data = response.json()  # Convert response to JSON

    # Extracting the list of ads
    posts = data.get('widget_list', [])

    titles = []
    areas = []
    rooms = []
    prices_deposit = []
    prices_rent = []

    # Loop through each post and extract info
    for post in posts:
        data_layer = post.get('data', {})
        
        title = data_layer.get('title')
        metas = data_layer.get('metas', {})

        area = metas.get('area')
        room = metas.get('room_count')
        deposit = metas.get('deposit')
        rent = metas.get('rent')

        titles.append(title)
        areas.append(area)
        rooms.append(room)
        prices_deposit.append(deposit)
        prices_rent.append(rent)

    # Create DataFrame
    df_api = pd.DataFrame({
        'عنوان': titles,
        'مساحت': areas,
        'اتاق': rooms,
        'ودیعه': prices_deposit,
        'اجاره': prices_rent
    })

    print("✅ تعداد آگهی‌های استخراج شده:", len(df_api))
    display(df_api.head())

else:
    print("❌ درخواست ناموفق. کد وضعیت:", response.status_code)

❌ درخواست ناموفق. کد وضعیت: 404

In [12]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # مرورگر بدون نمایش
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# چند ثانیه صبر کن تا صفحه لود شود
time.sleep(5)

# پیدا کردن آگهی‌ها
listings = driver.find_elements(By.CSS_SELECTOR, 'div.post-card-item-af972')

titles = []
areas = []
prices = []

for listing in listings:
    try:
        title = listing.find_element(By.CSS_SELECTOR, 'h2.kt-post-card__title').text
    except:
        title = None

    try:
        area = listing.find_element(By.CSS_SELECTOR, 'div.kt-post-card__bottom-description:nth-child(1)').text.replace('متر', '').strip()
    except:
        area = None

    try:
        price = listing.find_element(By.CSS_SELECTOR, 'div.kt-post-card__description').text.strip()
    except:
        price = None

    titles.append(title)
    areas.append(area)
    prices.append(price)

# ساخت DataFrame
df_selenium = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_selenium))
display(df_selenium.head())

# بستن مرورگر
driver.quit()

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, قیمت]
Index: []

In [13]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # مرورگر بدون نمایش
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# چند ثانیه صبر کن تا صفحه لود شود
time.sleep(5)

# پیدا کردن تمام div ها (یا یک کلاس مشترک)
elements = driver.find_elements(By.TAG_NAME, 'div')

# فقط 10 تا از div ها رو چاپ کنیم که بتونیم ساختار HTML رو بفهمیم
print("🔍 چند نمونه از div های موجود در صفحه:")
for i, el in enumerate(elements[:10]):
    print(f"{i+1}. {el.get_attribute('class')} | {el.text[:100]}...")

# بستن مرورگر
driver.quit()

🔍 چند نمونه از div های موجود در صفحه:
1.  | تهران
دسته‌ها
دستیار خرید
آزمایشی
دستیار خرید (آزمایشی)
دیوار من
چت
پشتیبانی
ثبت آگهی
۷۵,۱۶۸ آگهی در...
2.  | ...
3. a11y-menu__container-eac90 | ...
4. kt-rich-tooltip__trigger | تهران...
5. nav-bar__category-mega-box | دسته‌ها
دستیار خرید
آزمایشی
دستیار خرید (آزمایشی)
دیوار من
چت
پشتیبانی
ثبت آگهی...
6. kt-dropdown-menu category-mega-dropdown-f35f1 | دسته‌ها...
7. nav-bar__search-container | ...
8.  | ...
9. full-width kt-nav-text-field | ...
10. kt-nav-text-field__field | ...

In [14]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # مرورگر بدون نمایش
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# چند ثانیه صبر کن تا صفحه لود شود
time.sleep(5)

# پیدا کردن تمام div ها
elements = driver.find_elements(By.TAG_NAME, 'div')

# فیلتر کردن div هایی که محتوایشون شامل "اجاره آپارتمان" است
print("🔍 div هایی که شامل عبارت 'اجاره آپارتمان' هستند:")
found = False
for el in elements:
    text = el.text.strip()
    if 'اجاره آپارتمان' in text:
        print(f"- {text[:100]}...")
        found = True

if not found:
    print("❌ هیچ آگهی اجاره آپارتمانی پیدا نشد.")

# بستن مرورگر
driver.quit()

🔍 div هایی که شامل عبارت 'اجاره آپارتمان' هستند:
❌ هیچ آگهی اجاره آپارتمانی پیدا نشد.

In [15]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.XPATH, '//div[contains(@class, "kt-post-card__title")]'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند. صفحه شاید تغییر کرده.")

# پیدا کردن تمام آگهی‌ها با XPath دینامیک
listings = driver.find_elements(By.XPATH, '//div[contains(@class, "post-card-item")]')

titles = []
areas = []
prices = []

print(f"✅ {len(listings)} آگهی پیدا شد. در حال استخراج...")

for listing in listings:
    try:
        title = listing.find_element(By.XPATH, './/h2[contains(@class, "kt-post-card__title")]').text
    except:
        title = None

    try:
        area = listing.find_element(By.XPATH,
                                     './/div[contains(@class, "kt-post-card__bottom-description") and contains(text(), "متر")]').text.replace(
            'متر', '').strip()
    except:
        area = None

    try:
        price = listing.find_element(By.XPATH,
                                      './/div[contains(@class, "kt-post-card__description")]').text.strip()
    except:
        price = None

    titles.append(title)
    areas.append(area)
    prices.append(price)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head())

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
❌ المان‌های آگهی پیدا نشدند. صفحه شاید تغییر کرده.
✅ 0 آگهی پیدا شد. در حال استخراج...

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, قیمت]
Index: []

In [17]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند. صفحه شاید تغییر کرده.")

# پیدا کردن تمام آگهی‌ها با CSS Selector
listings = driver.find_elements(By.CSS_SELECTOR, 'div.unsafe-kt-post-card')

titles = []
areas = []
prices = []

print(f"✅ {len(listings)} آگهی پیدا شد. در حال استخراج...")

for listing in listings:
    try:
        title = listing.find_element(By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title').text
    except:
        title = None

    try:
        # پیدا کردن مساحت (مثال: "205 متر")
        area_text = listing.find_element(By.CSS_SELECTOR, 'div.unsafe-kt-post-card__description').text
        if 'متر' in area_text:
            area = area_text.split('متر')[0].strip()
        else:
            area = None
    except:
        area = None

    try:
        # پیدا کردن قیمت (مثال: "و دیعه: ۲,۲۰۰,۰۰۰,۰۰۰ تومان")
        price_text = listing.find_element(By.CSS_SELECTOR, 'div.unsafe-kt-post-card__description').text
        if 'و دیعه:' in price_text:
            price = price_text.split('و دیعه: ')[1].split(' تومان')[0].replace(',', '').strip()
        elif 'اجاره:' in price_text:
            price = price_text.split('اجاره: ')[1].split(' تومان')[0].replace(',', '').strip()
        else:
            price = None
    except:
        price = None

    titles.append(title)
    areas.append(area)
    prices.append(price)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head())

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
✅ المان‌های آگهی پیدا شدند.
✅ 0 آگهی پیدا شد. در حال استخراج...

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, قیمت]
Index: []

In [18]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند.")

# ⬇️ اسکرول کردن به پایین برای لود تمام آگهی‌ها
print("⬇️ در حال اسکرول کردن به پایین...")
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(3)  # صبر کن تا محتوا لود بشه

# پیدا کردن تمام آگهی‌ها با CSS Selector (فقط h2 ها رو تست می‌کنیم)
all_titles = driver.find_elements(By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title')

titles = []
areas = []
prices = []

print(f"✅ {len(all_titles)} آگهی پیدا شد. در حال استخراج...")

for title in all_titles:
    titles.append(title.text)

# چون فقط عنوان رو می‌تونیم بگیریم، دیگه متغیرهای دیگه None می‌شن
areas = [None] * len(titles)
prices = [None] * len(titles)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head())

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
✅ المان‌های آگهی پیدا شدند.
⬇️ در حال اسکرول کردن به پایین...
✅ 6 آگهی پیدا شد. در حال استخراج...

✅ تعداد آگهی‌های استخراج شده: 6

                                              عنوان مساحت  قیمت
0  اجاره آپارتمان ۶۰ متری ۲ خوابه طبقه ۴ در باغ فیض  None  None
1  ۲۷۰متر نوساز / برند /فول مشاعات /لوکیشن تاپ دروس  None  None
2               ۵۵ کارون طوس طبقه1نزدیک مترو شادمان  None  None
3                                   ۱۶۰متر رهن کامل  None  None
4                     پاسداران ۱۵۵متر/نوساز/تکواحدی  None  None

In [19]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd
import re

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک
url = "https://divar.ir/s/tehran/rent-apartment "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند.")

# ⬇️ اسکرول چندباره به پایین
for i in range(3):  # 3 بار اسکرول کن
    print(f"⬇️ اسکرول #{i+1}")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # صبر کن تا محتوا لود بشه

# پیدا کردن تمام آگهی‌ها
all_titles = driver.find_elements(By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title')

titles = [title.text for title in all_titles]

# استخراج مساحت از عنوان
def extract_area(title):
    match = re.search(r'(\d+)[\s\/]*متر', title)
    return int(match.group(1)) if match else None

areas = [extract_area(title) for title in titles]

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
✅ المان‌های آگهی پیدا شدند.
⬇️ اسکرول #1
⬇️ اسکرول #2
⬇️ اسکرول #3

✅ تعداد آگهی‌های استخراج شده: 6

                                            عنوان  مساحت
0  اپارتمان ۵۵متر یکخوابه طبقه اول جنت اباد مرکزی     55
1       فرمانیه غربی 110 متر ۳ خواب ۸۵ متر ۲ خواب    110
2            ۷۵متر/سعادت آباد/صراف شمالی/خوش نقشه     75
3         میرداماد150متر/3خواب/تکواحدی/قابل تبدیل    150
4               خواجه عبدالله ۱۶۰ متر ۳خواب نوساز    160
5                        75 متری کوچه اشرفی زاده.     75

In [20]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd
import re

# تنظیمات مرورگر
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--start-maximized')  # باز کردن مرورگر در حالت Fullscreen

# شروع مرورگر
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# باز کردن لینک جدید
url = "https://divar.ir/s/tehran/rent-apartment/jeyhoon?districts=1001%2C1002%2C1006%2C654%2C195%2C197%2C196%2C1029%2C284%2C1005%2C312&map_bbox=51.354522705078125%2C35.66758728027344%2C51.37498474121094%2C35.700321197509766&map_interaction=list_only_used&map_place_hash=1%7C1001%2C1002%2C1006%2C657%7Capartment-rent "
driver.get(url)

# صبر کن تا صفحه کامل لود بشه
print("⏳ صبر کن تا صفحه لود بشه...")
time.sleep(5)

# منتظر بمان تا المان‌های آگهی ظاهر شوند
try:
    WebDriverWait(driver, 20).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title'))
    )
    print("✅ المان‌های آگهی پیدا شدند.")
except:
    print("❌ المان‌های آگهی پیدا نشدند.")

# ⬇️ اسکرول چندباره به پایین
for i in range(5):  # 5 بار اسکرول کن
    print(f"⬇️ اسکرول #{i+1}")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)  # صبر کن تا محتوا لود بشه

# پیدا کردن تمام آگهی‌ها
all_titles = driver.find_elements(By.CSS_SELECTOR, 'h2.unsafe-kt-post-card__title')

titles = [title.text for title in all_titles]

# استخراج مساحت از عنوان
def extract_area(title):
    match = re.search(r'(\d+)[\s\/]*متر', title)
    return int(match.group(1)) if match else None

areas = [extract_area(title) for title in titles]

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas
})

print("\n✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

# بستن مرورگر
driver.quit()

⏳ صبر کن تا صفحه لود بشه...
✅ المان‌های آگهی پیدا شدند.
⬇️ اسکرول #1
⬇️ اسکرول #2
⬇️ اسکرول #3
⬇️ اسکرول #4
⬇️ اسکرول #5

✅ تعداد آگهی‌های استخراج شده: 6

                                               عنوان  مساحت
0                     اجاره آپارتمان نقلی و خوش نقشه    NaN
1      ۸۸متر فول امکانات/ کلیدنخورده/ تک واحدی/تخلیه   88.0
2              50متر/فول/پارکینگ موتور/جیحون، مرتضوی   50.0
3  اجاره هوم آفیس،۴۰ متر، ثبت وامکان گرفتن وام اجاره   40.0
4  ۵۳ متر تکواحدی با پارکینگ غیر مزاحم. سالن پرده...   53.0
5                 اپارتمان۶۴متر/ارومیه/تکخواب/دسترسی   64.0

In [22]:
import requests
from bs4 import BeautifulSoup
import json
import re
import pandas as pd

# URL صفحه
url = "https://divar.ir/s/tehran/rent-apartment "

# درخواست به سرور
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# پیدا کردن بلاک JSON
script_tag = soup.find('script', {'id': '__NEXT_DATA__'})
data = json.loads(script_tag.string)

# مسیر داده‌های آگهی
posts = data['props']['pageProps']['webAdList']['listData']

titles = []
areas = []
prices = []

for post in posts:
    title = post.get("title")
    description = post.get("description")
    
    titles.append(title)
    
    # استخراج مساحت
    area_match = re.search(r'(\d+)[\s\/]*متر', description) if description else None
    areas.append(int(area_match.group(1)) if area_match else None)
    
    # استخراج قیمت (مثال: "ودیعه: ۲,۵۰۰,۰۰۰,۰۰۰ تومان")
    price_match = re.search(r'ودیعه:\s*([\d\,]+)\s*تومان', description) if description else None
    prices.append(price_match.group(1).replace(',', '') if price_match else None)

# ساخت DataFrame
df_json = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'قیمت': prices
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_json))
display(df_json.head(10))

AttributeError: 'NoneType' object has no attribute 'string'

In [24]:
import re
import json
import pandas as pd

# خواندن فایل یا متن HTML
with open('Pasted_Text_1747572450500.txt', 'r', encoding='utf-8') as f:
    html_content = f.read()

# پیدا کردن تمام بلاک‌های JSON با regex
pattern = r'"token":"([^"]+)","title":"([^"]*)","description":"([^"]*)"'
matches = re.findall(pattern, html_content)

titles = []
descriptions = []
areas = []
prices = []

for match in matches:
    token, title, description = match
    
    titles.append(title)
    descriptions.append(description)
    
    # استخراج مساحت
    area_match = re.search(r'(\d+)[\s\/]*متر', title + " " + description)
    areas.append(int(area_match.group(1)) if area_match else None)
    
    # استخراج قیمت (ودیعه)
    price_match = re.search(r'ودیعه:\s*([\d\,]+)\s*تومان', description)
    prices.append(price_match.group(1).replace(',', '') if price_match else None)

# ساخت DataFrame
df_regex = pd.DataFrame({
    'عنوان': titles,
    'توضیحات': descriptions,
    'مساحت': areas,
    'قیمت': prices
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_regex))
display(df_regex[['عنوان', 'مساحت', 'قیمت']])

FileNotFoundError: [Errno 2] No such file or directory: 'Pasted_Text_1747572450500.txt'

In [25]:
import re
import pandas as pd

# ⬇️ اینجا متن HTML رو مستقیم درون کد گذاشتیم
html_content = """
<script>window.__PRELOADED_STATE__ = {"nb":{"listTopWidgets":[{"widgetType":"POST_LIST_HEADLINE","text":"اجاره و رهن آپارتمان، خانه و سوییت در زنجان و ۱۱ محلهٔ دیگر تهران","KEY_PROP_NAME":"efdf926f-cf77-4f3a-aff2-5b397a66d8e8","visibilityConditions":[]}],"listWidgets":[{"type":"WIDGET","data":{"widgetType":"POST_ROW","token":"Aao4yg-A","title":"همخونه همخانه نیازمندم","topDescription":"ودیعه: ۵۰,۰۰۰,۰۰۰ تومان","middleDescription":"اجاره: ۶,۰۰۰,۰۰۰ تومان","bottomDescription":"در دکتر هوشیار","redText":"پله شده","action":{"as":"link"

...

متر، ثبت وامکان گرفتن وام اجاره"},{"name":"۵۳ متر تکواحدی با پارکینگ غیر مزاحم. سالن پرده خور","url":"https://divar.ir/v/ ۵۳-متر-تکواحدی-با-پارکینگ-غیر-مزاحم-سالن-پرده-خور/AapUthb7","accommodationCategory":"آپارتمان","@context":"https://schema.org ","numberOfRooms":"یک","floorSize":{"@type":"QuantitativeValue","value":"53","unitCode":"MTK"},"geo":{"address":"تهران, جیحون","latitude":"35.691192501346","longitude":"51.366855079884","@type":"GeoCoordinates"},"web_info":{"title":"۵۳ متر تکواحدی با پارکینگ غیر مزاحم. سالن پرده خور","city_persian":"تهران"
...
"""

# الگو برای استخراج JSON‌های مهم شامل title و قیمت و مساحت
pattern = r'"token":"([^"]+)","title":"([^"]*)","description":"([^"]*)"'
matches = re.findall(pattern, html_content)

titles = []
areas = []
prices_deposit = []
prices_rent = []

for match in matches:
    token, title, description = match

    titles.append(title)

    # 🔍 استخراج مساحت
    area = None
    area_match = re.search(r'"floorSize":\{"@type":"QuantitativeValue","value":"(\d+)"', description + title + html_content)
    if area_match:
        area = int(area_match.group(1))
    areas.append(area)

    # 🔍 استخراج قیمت (ودیعه)
    deposit_price = None
    deposit_match = re.search(r'ودیعه:\s*([\d\,]+)\s*تومان', description)
    if deposit_match:
        deposit_price = deposit_match.group(1).replace(',', '')
    prices_deposit.append(deposit_price)

    # 🔍 استخراج قیمت (اجاره)
    rent_price = None
    rent_match = re.search(r'اجاره:\s*([\d\,]+)\s*تومان', description)
    if rent_match:
        rent_price = rent_match.group(1).replace(',', '')
    prices_rent.append(rent_price)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'ودیعه': prices_deposit,
    'اجاره': prices_rent
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, ودیعه, اجاره]
Index: []

In [26]:
import re
import pandas as pd

# خواندن فایل txt با رمزگذاری درست
file_path = 'Pasted_Text_1747572949033.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# پیدا کردن تمام آگهی‌ها با regex
pattern = r'"token":"([^"]+)","title":"([^"]*)","topDescription":"([^"]*)","middleDescription":"([^"]*)","bottomDescription":"([^"]*)"'
matches = re.findall(pattern, content)

titles = []
areas = []
deposits = []
rents = []
locations = []

for match in matches:
    token, title, top_desc, middle_desc, bottom_desc = match

    titles.append(title)
    locations.append(bottom_desc)

    # 🔍 استخراج مساحت از عنوان یا توضیحات
    area_match = re.search(r'(\d+)\s*متر', title + " " + top_desc + " " + middle_desc)
    areas.append(int(area_match.group(1)) if area_match else None)

    # 🔍 استخراج ودیعه
    deposit_match = re.search(r'ودیعه:\s*([\d\,]+)\s*تومان', top_desc)
    deposits.append(deposit_match.group(1).replace(',', '') if deposit_match else None)

    # 🔍 استخراج اجاره
    rent_match = re.search(r'اجاره:\s*([\d\,]+)\s*تومان', middle_desc)
    rents.append(rent_match.group(1).replace(',', '') if rent_match else None)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'ودیعه': deposits,
    'اجاره': rents,
    'موقعیت': locations
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 26

,عنوان,مساحت,ودیعه,اجاره,موقعیت
0,همخونه همخانه نیازمندم,NaN,۵۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,در دکتر هوشیار
1,۸۸متر فول امکانات\u002F کلیدنخورده\u002F تک وا...,88.0,۱۱۷۰۰۰۰۰۰۰,None,مشاورین املاک گل محمدی شعبه ۲ در جیحون
2,50متر\u002Fفول\u002Fپارکینگ موتور\u002Fجیحون، ...,50.0,۱۵۰۰۰۰۰۰۰,۱۳۰۰۰۰۰۰,آژانس املاک همپا در جیحون
3,اجاره هوم آفیس،۴۰ متر، ثبت وامکان گرفتن وام اجاره,40.0,۱۳۰۰۰۰۰۰۰,۱۰۵۰۰۰۰۰,دقایقی پیش در هفت چنار
4,۵۳ متر تکواحدی با پارکینگ غیر مزاحم. سالن پرده...,53.0,۲۵۰۰۰۰۰۰۰,۱۱۵۰۰۰۰۰,آژانس مشاورین املاک طهرانی در جیحون
5,اپارتمان۶۴متر\u002Fارومیه\u002Fتکخواب\u002Fدسترسی,64.0,۸۰۰۰۰۰۰۰۰,۱۰۰۰۰۰,املاک حافظ در آذربایجان
6,۵۰ متر\u002Fفول امکانات\u002Fغرق نور,50.0,۳۵۰۰۰۰۰۰۰,۸۵۰۰۰۰۰,مشاور اسدی در استاد معین
7,۴۲ متر‌\u002Fپارکینگ غیر مزاحم\u002Fکردکاظمی ب...,42.0,۳۰۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,آژانس املاک خانه برتر در بریانک
8,۶۵متر\u002Fبازسازی\u002Fتکواحدی\u002Fآذربایجان,65.0,۳۵۰۰۰۰۰۰۰,۱۶۰۰۰۰۰۰,گروه مشاورین املاک آفرند در آذربایجان
9,۵۵ کارون طوس طبقه1نزدیک مترو شادمان,NaN,۲۰۰۰۰۰۰۰۰,۱۲۰۰۰۰۰۰,آژانس املاک طلوع در جیحون

In [30]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'pasted_divar_data.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# الگوهای regex برای استخراج اطلاعات
title_matches = re.findall(r'"name":"([^"]+)"', content)
area_matches = re.findall(r'"value":"(\d+)\s*متر"', content)
deposit_matches = re.findall(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', content)
rent_matches = re.findall(r'اجاره:\s*(\d[\d\,]*)\s*تومان', content)

# استخراج تمام داده‌ها با regex عمومی‌تر (در صورت نیاز)
general_title_matches = re.findall(r'alt="([^"]+)"', content)

# ترکیب همه عنوان‌ها
all_titles = title_matches + general_title_matches

# تنظیم طول لیست‌ها به یک اندازه
min_len = min(len(all_titles), len(area_matches), len(deposit_matches), len(rent_matches))

titles = all_titles[:min_len]
areas = area_matches[:min_len]
deposits = deposit_matches[:min_len]
rents = rent_matches[:min_len]

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': titles,
    'مساحت': areas,
    'ودیعه': deposits,
    'اجاره': rents
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, ودیعه, اجاره]
Index: []

In [31]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'pasted_divar_data.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# الگوهای Regex برای استخراج
title_matches = re.findall(r'"title":"(.*?)"', content)
top_descs = re.findall(r'"topDescription":"(.*?)"', content)
mid_descs = re.findall(r'"middleDescription":"(.*?)"', content)
bot_descs = re.findall(r'"bottomDescription":"(.*?)"', content)

# استخراج مساحت، ودیعه و اجاره
areas = []
deposits = []
rents = []
locations = []

for i in range(len(title_matches)):
    title = title_matches[i] if i < len(title_matches) else None
    top_desc = top_descs[i] if i < len(top_descs) else None
    mid_desc = mid_descs[i] if i < len(mid_descs) else None
    bot_desc = bot_descs[i] if i < len(bot_descs) else None

    # استخراج مساحت
    area_match = re.search(r'(\d+)\s*متر', title + " " + (top_desc or "") + " " + (mid_desc or ""))
    areas.append(int(area_match.group(1)) if area_match else None)

    # استخراج ودیعه
    deposit_match = re.search(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', top_desc or "")
    deposits.append(deposit_match.group(1).replace(',', '') if deposit_match else None)

    # استخراج اجاره
    rent_match = re.search(r'اجاره:\s*(\d[\d\,]*)\s*تومان', mid_desc or "")
    rents.append(rent_match.group(1).replace(',', '') if rent_match else None)

    # ذخیره موقعیت
    locations.append(bot_desc or None)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': title_matches,
    'مساحت': areas,
    'ودیعه': deposits,
    'اجاره': rents,
    'موقعیت': locations
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 118

,عنوان,مساحت,ودیعه,اجاره,موقعیت
0,همخونه همخانه نیازمندم,NaN,۵۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,در دکتر هوشیار
1,اجاره مشترک (همخونه),NaN,۱۰۰۰۰۰۰,۱۰۰۰۰۰,در استاد معین
2,اجاره آپارتمان ۴۴ متری ۱ خوابه طبقه ۲ در جیحون,44.0,۱۰۰۰۰۰۰۰۰,۱۴۰۰۰۰۰۰,دقایقی پیش در جیحون
3,۵۵ متر فول امکانات گذر ۱۰ متری بر اصلی,55.0,۶۰۰۰۰۰۰۰۰,None,دپارتمان کاوه در جی
4,اجاره آپارتمان ۵۸ متری ۱ خوابه در طوس,58.0,۷۰۰۰۰۰۰۰۰,۱۴۰۰۰۰۰۰,دقایقی پیش در دکتر هوشیار
5,60متر\u002F تک واحدی با پارکینگ\u002F۱۳ متری,60.0,۵۰۰۰۰۰۰۰۰,۳۰۰۰۰۰۰,دقایقی پیش در جی
6,بهنود یادگارطوس(نوساز)۱۰۶متر,106.0,۵۰۰۰۰۰۰۰۰,۲۵۰۰۰۰۰۰,در جیحون
7,۶۶متر\u002Fدوخواب\u002Fتکواحدی\u002Fآسانسور\u0...,66.0,۳۵۰۰۰۰۰۰۰,۱۵۰۰۰۰۰۰,دقایقی پیش در آذربایجان
8,۴۳متر \u002Fهمکف \u002Fفول بازسازی \u002F غرق نور,43.0,۲۵۰۰۰۰۰۰۰,۴۰۰۰۰۰۰,آژانس امید در سلیمانی
9,۷۰ متر ۲ خواب \u002F تک واحدی,70.0,۴۰۰۰۰۰۰۰۰,۵۰۰۰۰۰۰,مشاورین املاک احمدزاده در هفت چنار

In [32]:
# ذخیره در فایل CSV
df_final.to_csv('divar_rent_data.csv', index=False, encoding='utf-8-sig')
print("✅ فایل CSV با موفقیت ذخیره شد!")

✅ فایل CSV با موفقیت ذخیره شد!

In [33]:
import pandas as pd

# خواندن فایل CSV
df = pd.read_csv('divar_rent_data.csv')

# نمایش داده‌ها با شماره‌گذاری ردیف
df.index = df.index + 1  # شماره‌گذاری از ۱ شروع بشه
print("✅ داده‌های ذخیره شده در فایل CSV:")
display(df)

✅ داده‌های ذخیره شده در فایل CSV:

,عنوان,مساحت,ودیعه,اجاره,موقعیت
1,همخونه همخانه نیازمندم,NaN,۵۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,در دکتر هوشیار
2,اجاره مشترک (همخونه),NaN,۱۰۰۰۰۰۰,۱۰۰۰۰۰,در استاد معین
3,اجاره آپارتمان ۴۴ متری ۱ خوابه طبقه ۲ در جیحون,44.0,۱۰۰۰۰۰۰۰۰,۱۴۰۰۰۰۰۰,دقایقی پیش در جیحون
4,۵۵ متر فول امکانات گذر ۱۰ متری بر اصلی,55.0,۶۰۰۰۰۰۰۰۰,NaN,دپارتمان کاوه در جی
5,اجاره آپارتمان ۵۸ متری ۱ خوابه در طوس,58.0,۷۰۰۰۰۰۰۰۰,۱۴۰۰۰۰۰۰,دقایقی پیش در دکتر هوشیار
...,...,...,...,...,...
114,رهن ۴۷ متر - ۱خوابه - مرتضوی,47.0,NaN,NaN,NaN
115,آپارتمان ۴۰ متری,40.0,NaN,NaN,NaN
116,۱۰۸متر ۲خواب(پارکینگ،انباری)همکف/استادمعین پازوکی,108.0,NaN,NaN,NaN
117,65متر 1خواب فول بازسازی شده رهن کامل,65.0,NaN,NaN,NaN
118,رهن اجاره ۵۰ متر آپارتمان پارکینگدار سی متری جی,50.0,NaN,NaN,NaN

In [ ]:
# تنظیم pandas برای نمایش تمام ردیف‌ها
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# نمایش DataFrame
display(df_final)

In [35]:
import re
import json
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# الگو برای پیدا کردن بلاک JSON
json_match = re.search(r'window.__PRELOADED_STATE__\s*=\s*({.*?});', content, re.DOTALL)

if json_match:
    # تبدیل رشته JSON به دیکشنری
    try:
        json_str = json_match.group(1)
        data = json.loads(json_str)
        
        # استخراج لیست آگهی‌ها
        posts = data.get('props', {}).get('pageProps', {}).get('webAdList', {}).get('listData', [])
        
        titles = []
        areas = []
        deposits = []
        rents = []
        locations = []

        for post in posts:
            data_layer = post.get('data', {})
            
            title = data_layer.get('title')
            description = data_layer.get('description', '')
            bottom_desc = data_layer.get('bottom_description', '')

            titles.append(title)
            locations.append(bottom_desc)

            # استخراج مساحت
            area_match = re.search(r'(\d+)\s*متر', title + " " + description)
            areas.append(int(area_match.group(1)) if area_match else None)

            # استخراج ودیعه
            deposit_match = re.search(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', description)
            deposits.append(deposit_match.group(1).replace(',', '') if deposit_match else None)

            # استخراج اجاره
            rent_match = re.search(r'اجاره:\s*(\d[\d\,]*)\s*تومان', description)
            rents.append(rent_match.group(1).replace(',', '') if rent_match else None)

        # ساخت DataFrame
        df_house_rent = pd.DataFrame({
            'عنوان': titles,
            'مساحت': areas,
            'ودیعه': deposits,
            'اجاره': rents,
            'موقعیت': locations
        })

        print("✅ تعداد آگهی‌های استخراج شده:", len(df_house_rent))
        display(df_house_rent.head(10))

    except json.JSONDecodeError as e:
        print("❌ خطا در دکد کردن JSON:", e)
else:
    print("❌ داده JSON پیدا نشد")

✅ تعداد آگهی‌های استخراج شده: 0

Empty DataFrame
Columns: [عنوان, مساحت, ودیعه, اجاره, موقعیت]
Index: []

In [41]:
import json
import pandas as pd
import os

# Check current working directory
print("Current Working Directory:", os.getcwd())

# Define the correct file path
file_path = 'divar_fullrent.txt'  # Make sure this file exists in your folder

posts = []

# Open and read the file line by line
with open(file_path, 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        try:
            data = json.loads(line.strip())

            # Only process WIDGET type with POST_ROW widgetType
            if isinstance(data, dict) and data.get('type') == 'WIDGET':
                widget_data = data.get('data', {})
                if widget_data.get('widgetType') == 'POST_ROW':
                    post_info = {
                        'token': widget_data.get('token'),
                        'title': widget_data.get('title'),
                        'topDescription': widget_data.get('topDescription'),
                        'middleDescription': widget_data.get('middleDescription'),
                        'bottomDescription': widget_data.get('bottomDescription'),
                        'url_suffix': widget_data.get('action', {}).get('props', {}).get('to')
                    }
                    posts.append(post_info)

        except json.JSONDecodeError:
            continue  # Skip lines that can't be parsed

# Create DataFrame
df_posts = pd.DataFrame(posts)

# Show result
if not df_posts.empty:
    print("\n✅ Successfully loaded data:")
    display(df_posts.head())
else:
    print("\n❌ No valid data found. Please check the file content or structure.")

Current Working Directory: /Users/macbookpro/AMIR_DATA/00_Project/VSCode__project/1_Machine_learning/with_AI/ML_Models/simulation_upwork/real_estate_ml_analysis

❌ No valid data found. Please check the file content or structure.

In [42]:
import re
import json
import pandas as pd

# File path
file_path = 'divar_fullrent.txt'

# Read the full HTML content
with open(file_path, 'r', encoding='utf-8') as f:
    html_content = f.read()

# Find all JSON objects inside "window.__PRELOADED_STATE__" (where Divar stores its data)
match = re.search(r'window\.__PRELOADED_STATE__\s*=\s*({.*?});\s*\(function', html_content, re.DOTALL)

if match:
    try:
        # Load the main JSON data
        raw_json = match.group(1)
        data = json.loads(raw_json)

        # Navigate to the posts list
        posts_data = data.get('widgets', {}).get('list', [])

        posts = []
        for post in posts_data:
            if isinstance(post, dict) and post.get('widgetType') == 'POST_ROW':
                post_info = {
                    'token': post.get('token'),
                    'title': post.get('title'),
                    'topDescription': post.get('topDescription'),
                    'middleDescription': post.get('middleDescription'),
                    'bottomDescription': post.get('bottomDescription'),
                    'url_suffix': post.get('action', {}).get('props', {}).get('to')
                }
                posts.append(post_info)

        # Create DataFrame
        df_posts = pd.DataFrame(posts)
        
        if not df_posts.empty:
            print("✅ Successfully loaded data:")
            display(df_posts.head())
        else:
            print("❌ No POST_ROW widgets found in the JSON.")
    
    except json.JSONDecodeError as e:
        print("❌ Failed to parse JSON:", e)
else:
    print("❌ Could not find JSON data in HTML file.")

❌ Could not find JSON data in HTML file.

In [45]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# الگوهای Regex برای استخراج
title_matches = re.findall(r'"title":"(.*?)"', content)
top_descs = re.findall(r'"topDescription":"(.*?)"', content)
mid_descs = re.findall(r'"middleDescription":"(.*?)"', content)
bot_descs = re.findall(r'"bottomDescription":"(.*?)"', content)

# استخراج مساحت، ودیعه و اجاره
areas = []
deposits = []
rents = []
locations = []

for i in range(len(title_matches)):
    title = title_matches[i] if i < len(title_matches) else None
    top_desc = top_descs[i] if i < len(top_descs) else None
    mid_desc = mid_descs[i] if i < len(mid_descs) else None
    bot_desc = bot_descs[i] if i < len(bot_descs) else None

    # استخراج مساحت
    area_match = re.search(r'(\d+)\s*متر', title + " " + (top_desc or "") + " " + (mid_desc or ""))
    areas.append(int(area_match.group(1)) if area_match else None)

    # استخراج ودیعه
    deposit_match = re.search(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', top_desc or "")
    deposits.append(deposit_match.group(1).replace(',', '') if deposit_match else None)

    # استخراج اجاره
    rent_match = re.search(r'اجاره:\s*(\d[\d\,]*)\s*تومان', mid_desc or "")
    rents.append(rent_match.group(1).replace(',', '') if rent_match else None)

    # ذخیره موقعیت
    locations.append(bot_desc or None)

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': title_matches,
    'مساحت': areas,
    'ودیعه': deposits,
    'اجاره': rents,
    'موقعیت': locations
})

print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
display(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 107

,عنوان,مساحت,ودیعه,اجاره,موقعیت
0,خانه دربستی چهار خوابه,NaN,۷۰۰۰۰۰۰۰۰,۵۲۰۰۰۰۰,در نواب
1,۱۰۰ متر ۳ طبقه \u002Fخ آزادی جنب مترو توحید \u...,100.0,۵۰۰۰۰۰۰۰۰,۶۵۰۰۰۰۰۰,آژانس املاک بزرگ سناتور با ۲شعبه فعال در جیحون
2,خانه ویلایی ۲۵۰ متر,250.0,۴۰۰۰۰۰۰۰۰,۵۰۰۰۰۰۰۰,دقایقی پیش در استاد معین
3,100 متری \u002Fدر بستی\u002F,100.0,۷۵۰۰۰۰۰۰۰,۱۰۰۰۰۰,آژانس امید در هفت چنار
4,واحد دربست خانه 100متری دو طبقه جیحون سپه,100.0,۳۵۰۰۰۰۰۰۰,۲۸۰۰۰۰۰۰,املاک بزرگ نهال در جیحون
5,اجاره خانه ویلایی ۷۰ متری ۳ خوابه در جیحون,70.0,۴۵۰۰۰۰۰۰۰,۶۰۰۰۰۰۰,آژانس املاک دریا در جیحون
6,خانه نقلی۲۵ متری ۲طبقه دربست خانواده مجرد,25.0,۳۹۰۰۰۰۰۰۰,۱۰۰۰۰۰,۲ ساعت پیش در هاشمی
7,اجاره خانه ویلایی ۱۲۰ متری ۵ خوابه در جی,120.0,۴۰۰۰۰۰۰۰۰,۱۸۰۰۰۰۰۰,۲ ساعت پیش در جی
8,اجاره خانه ویلایی ۴۰ متری ۲ خوابه در استاد معین,40.0,۲۱۰۰۰۰۰۰۰,۱۰۰۰۰۰۰۰,۳ ساعت پیش در استاد معین
9,اجاره خانه ویلایی ۱۲ متری ۱ خوابه در سلسبیل,12.0,۲۰۰۰۰۰۰,۷۵۰۰۰۰۰,۴ ساعت پیش در سلسبیل

In [46]:
# ذخیره به صورت CSV
df_final.to_csv('real_estate_data.csv', index=False, encoding='utf-8-sig')
print("✅ دیتا با موفقیت در فایل 'real_estate_data.csv' ذخیره شد.")

✅ دیتا با موفقیت در فایل 'real_estate_data.csv' ذخیره شد.

In [47]:
# ذخیره به صورت pickle
df_final.to_pickle('real_estate_data.pkl')
print("✅ دیتا با موفقیت در فایل 'real_estate_data.pkl' ذخیره شد.")

✅ دیتا با موفقیت در فایل 'real_estate_data.pkl' ذخیره شد.

In [ ]:
# نمایش تمام ردیف‌ها در Jupyter
pd.set_option('display.max_rows', None)
display(df_final)

In [51]:
import re
import json
import pandas as pd

# ۱. خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as f:
    html_content = f.read()

# ۲. الگوی دقیق‌تر برای پیدا کردن JSON دیوار
match = re.search(r'window\.__PRELOADED_STATE__\s*=\s*(\{.*?\});', html_content, re.DOTALL)

if match:
    try:
        # ۳. استخراج JSON و لود کردن
        raw_json = match.group(1)
        
        # ۴. تبدیل به دیکشنری پایتون
        data = json.loads(raw_json)

        # ۵. دسترسی به لیست آگهی‌ها
        posts_data = data.get('widgets', {}).get('list', [])

        # ۶. استخراج فیلدهای مهم
        posts = []
        for post in posts_data:
            if isinstance(post, dict) and post.get('widgetType') == 'POST_ROW':
                token = post.get('token')
                title = post.get('title')
                top_desc = post.get('topDescription')
                mid_desc = post.get('middleDescription')
                bot_desc = post.get('bottomDescription')

                # استخراج مساحت، ودیعه، اجاره
                area_match = re.search(r'(\d+)\s*(?:متر|متري)', title + " " + (top_desc or "") + " " + (mid_desc or ""))
                area = int(area_match.group(1)) if area_match else None

                deposit_match = re.search(r'ودیعه:\s*(\d[\d\,]*)\s*تومان', top_desc or "")
                deposit = deposit_match.group(1).replace(',', '') if deposit_match else None

                rent_match = re.search(r'اجاره:\s*(\d[\d\,]*)\s*تومان', mid_desc or "")
                rent = rent_match.group(1).replace(',', '') if rent_match else None

                # ذخیره موقعیت
                location = bot_desc

                posts.append({
                    'token': token,
                    'عنوان': title,
                    'مساحت': area,
                    'ودیعه': deposit,
                    'اجاره': rent,
                    'موقعیت': location
                })

        # ۷. ساخت DataFrame
        df_final = pd.DataFrame(posts)

        # ۸. تبدیل اعداد فارسی به انگلیسی
        def fa_to_en_numbers(text):
            if not isinstance(text, str):
                return text
            fa_digits = '۰۱۲۳۴۵۶۷۸۹'
            en_digits = '0123456789'
            translation_table = str.maketrans(fa_digits, en_digits)
            return text.translate(translation_table)

        df_final['ودیعه'] = df_final['ودیعه'].apply(fa_to_en_numbers)
        df_final['اجاره'] = df_final['اجاره'].apply(fa_to_en_numbers)

        # ۹. ذخیره به CSV
        df_final.to_csv('real_estate_data_clean.csv', index=False, encoding='utf-8-sig')
        print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
        print(df_final.head(10))

    except json.JSONDecodeError as e:
        print("❌ خطا در خواندن JSON:", e)
else:
    print("❌ JSON دیوار در فایل پیدا نشد.")

KeyError: 'ودیعه'

In [52]:
print("✅ ستون‌های DataFrame:")
print(df_final.columns.tolist())

✅ ستون‌های DataFrame:
[]

In [54]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    html_content = file.read()

# الگوهای Regex برای استخراج
title_matches = re.findall(r'alt="([^"]+)"', html_content)
price_deposit = re.findall(r'ودیعه:\s*([\d۰-۹,]+)\s*تومان', html_content)
price_rent = re.findall(r'اجاره:\s*([\d۰-۹,]+)\s*تومان', html_content)
area_matches = re.findall(r'(\d+)\s*متر', ' '.join(title_matches))

# تابع تبدیل عدد فارسی به انگلیسی
def fa_to_en_numbers(text):
    if not isinstance(text, str):
        return text
    fa_digits = '۰۱۲۳۴۵۶۷۸۹'
    en_digits = '0123456789'
    translation_table = str.maketrans(fa_digits, en_digits)
    return text.translate(translation_table)

# استخراج موقعیت از عنوان (مثلاً "املاک کاندید در آذربایجان")
location_matches = []
for title in title_matches:
    loc_match = re.search(r'(?:در|در منطقه|در محله|،|\.|در)\s*([آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]{2,})', title)
    location_matches.append(loc_match.group(1).strip() if loc_match else None)

# تنظیم اعداد فارسی به انگلیسی
cleaned_areas = [int(fa_to_en_numbers(area)) if area else None for area in area_matches]
cleaned_deposits = [int(fa_to_en_numbers(dep).replace(',', '')) if dep else None for dep in price_deposit]
cleaned_rents = [int(fa_to_en_numbers(rent).replace(',', '')) if rent else None for rent in price_rent]

# ساخت DataFrame
df_final = pd.DataFrame({
    'عنوان': title_matches,
    'مساحت': cleaned_areas,
    'ودیعه': cleaned_deposits,
    'اجاره': cleaned_rents,
    'موقعیت': location_matches
})

# ذخیره به CSV
df_final.to_csv('real_estate_data_final.csv', index=False, encoding='utf-8-sig')

# نمایش خروجی
print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
print(df_final.head(10))

ValueError: All arrays must be of the same length

In [55]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    html_content = file.read()

# الگو برای پیدا کردن هر آگهی
post_pattern = re.compile(
    r'<.*?alt="(.*?)".*?(?:ودیعه:\s*([\d۰-۹,]+)\s*تومان)?.*?(?:اجاره:\s*([\d۰-۹,]+)\s*تومان)?.*?(?:(\d+)\s*متر).*?(?:در|در منطقه|در محله|،|\.|در)\s*([آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]{2,})', 
    re.DOTALL
)

# استخراج اطلاعات همزمان
posts = []
for match in post_pattern.finditer(html_content):
    title = match.group(1)
    deposit = match.group(2)
    rent = match.group(3)
    area = match.group(4)
    location = match.group(5)

    posts.append({
        'عنوان': title.strip() if title else None,
        'مساحت': int(area) if area else None,
        'ودیعه': deposit.strip() if deposit else None,
        'اجاره': rent.strip() if rent else None,
        'موقعیت': location.strip() if location else None
    })

# ساخت DataFrame
df_final = pd.DataFrame(posts)

# تبدیل عدد فارسی به انگلیسی
def fa_to_en_numbers(text):
    if not isinstance(text, str):
        return text
    fa_digits = '۰۱۲۳۴۵۶۷۸۹'
    en_digits = '0123456789'
    translation_table = str.maketrans(fa_digits, en_digits)
    return text.translate(translation_table)

df_final['ودیعه'] = df_final['ودیعه'].apply(lambda x: fa_to_en_numbers(x).replace(',', '') if isinstance(x, str) else x)
df_final['اجاره'] = df_final['اجاره'].apply(lambda x: fa_to_en_numbers(x).replace(',', '') if isinstance(x, str) else x)

# ذخیره به CSV
df_final.to_csv('real_estate_data_final.csv', index=False, encoding='utf-8-sig')

# نمایش خروجی
print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
print(df_final.head(10))

✅ تعداد آگهی‌های استخراج شده: 14
                                             عنوان  مساحت ودیعه اجاره  \
0                                       نشان دیوار    100  None  None
1  ۱۰۰ متر ۳ طبقه /خ آزادی جنب مترو توحید /پارکینگ    250  None  None
2                              خانه ویلایی ۲۵۰ متر    100  None  None
3                               100 متری /در بستی/    100  None  None
4       واحد دربست خانه 100متری دو طبقه  جیحون سپه     70  None  None
5  اجاره خانه ویلایی ۴۰ متری ۲ خوابه در استاد معین     12  None  None
6      اجاره خانه ویلایی ۱۲ متری ۱ خوابه در سلسبیل    120  None  None
7               ۱۲۰متر چهار خواب خوش نرسیده به طوس    100  None  None
8               ۱۰۰ متر/کلنگی/سینا غربی/مترو کمیل/    150  None  None
9                  150 متر فول بازسازی کمیل شیرازی    150  None  None

       موقعیت
0       جیحون
1  استاد معین
2        بستی
3    بست خانه
4       جیحون
5      سلسبیل
6   آذربایجان
7        نواب
8    هفت چنار
9     بستی در

In [ ]:
import re
import pandas as pd

# خواندن فایل txt
file_path = 'divar_fullrent.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    html_content = file.read()

# الگو برای پیدا کردن هر آگهی با regex هوشمندانه
post_pattern = re.compile(
    r'alt="(.*?)".*?(?:ودیعه:\s*([\d۰-۹,]+)\s*تومان)?.*?(?:اجاره:\s*([\d۰-۹,]+)\s*تومان)?.*?(\d+)\s*متر.*?(?:در|،|\.|در منطقه|در محله)\s*([آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئ\s]{2,})',
    re.DOTALL
)

posts = []

for match in post_pattern.finditer(html_content):
    title = match.group(1)
    deposit = match.group(2)
    rent = match.group(3)
    area = match.group(4)
    location = match.group(5)

    posts.append({
        'عنوان': title.strip() if title else None,
        'مساحت': int(area) if area else None,
        'ودیعه': deposit.strip() if deposit else None,
        'اجاره': rent.strip() if rent else None,
        'موقعیت': location.strip() if location else None
    })

# تبدیل عدد فارسی به انگلیسی
def fa_to_en_numbers(text):
    if not isinstance(text, str):
        return text
    fa_digits = '۰۱۲۳۴۵۶۷۸۹'
    en_digits = '0123456789'
    translation_table = str.maketrans(fa_digits, en_digits)
    return text.translate(translation_table)

df_final = pd.DataFrame(posts)
df_final['ودیعه'] = df_final['ودیعه'].apply(lambda x: fa_to_en_numbers(x).replace(',', '') if isinstance(x, str) and x else x)
df_final['اجاره'] = df_final['اجاره'].apply(lambda x: fa_to_en_numbers(x).replace(',', '') if isinstance(x, str) and x else x)

# ذخیره دیتا
df_final.to_csv('real_estate_data_final.csv', index=False, encoding='utf-8-sig')

# نمایش خروجی
print("✅ تعداد آگهی‌های استخراج شده:", len(df_final))
print(df_final)

✅ تعداد آگهی‌های استخراج شده: 14
                                                عنوان  مساحت ودیعه اجاره  \
0                                          نشان دیوار    100  None  None
1     ۱۰۰ متر ۳ طبقه /خ آزادی جنب مترو توحید /پارکینگ    250  None  None
2                                 خانه ویلایی ۲۵۰ متر    100  None  None
3                                  100 متری /در بستی/    100  None  None
4          واحد دربست خانه 100متری دو طبقه  جیحون سپه     70  None  None
5     اجاره خانه ویلایی ۴۰ متری ۲ خوابه در استاد معین     12  None  None
6         اجاره خانه ویلایی ۱۲ متری ۱ خوابه در سلسبیل    120  None  None
7                  ۱۲۰متر چهار خواب خوش نرسیده به طوس    100  None  None
8                  ۱۰۰ متر/کلنگی/سینا غربی/مترو کمیل/    150  None  None
9                     150 متر فول بازسازی کمیل شیرازی    150  None  None
10  ۱۵۰ متر واحد دربستی در ۲ طبقه کاملا مجزا . با ...    300  None  None
11       ویلایی ۳۰۰ متری ۵ خوابه در نزدیک مترو شادمان     50  None  None
12        ۲طبقه دربست ۵۰ متری سرویس کامل مرتضوی جیحون    120  None  None
13                       ۱۲۰ متر دربستی دوطبقه بریانک    100  None  None

                موقعیت
0                جیحون
1           استاد معین
2                 بستی
3             بست خانه
4                جیحون
5               سلسبیل
6            آذربایجان
7                 نواب
8             هفت چنار
9              بستی در
10   نزدیک مترو شادمان
11               جیحون
12  بستی دوطبقه بریانک
13                باره